import React,{useEffect,useMemo,useState} from 'react';
import {Bar,BarChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {CalendarDays,Download,Plus,Save,Users,X} from 'lucide-react';
import {motion} from 'framer-motion';
import {adminApi,eventsApi,studentsApi} from '../api/client';
import {useAuth} from '../context/AuthContext';
import {useToast} from '../context/ToastContext';
import {Badge,Button,Card,Input,Modal,SkillChip} from '../components/ui';
import {GradientIcon} from '../components/GradientIcon';
import {Avatar} from '../components/ui';
import {TableRowSkeleton} from '../components/Skeleton';

const blank={title:'',organizer:'',category:'Hackathon',scope:'Inter-college',mode:'Hybrid',date:'2026-12-01',deadline:'2026-11-24',teamSize:'2–4',description:'',skills:'React, Python',color:'sage'};
const chartFallback=[{day:'Mon',signups:24,registrations:18},{day:'Tue',signups:38,registrations:25},{day:'Wed',signups:31,registrations:33},{day:'Thu',signups:54,registrations:29},{day:'Fri',signups:49,registrations:47},{day:'Sat',signups:72,registrations:56},{day:'Sun',signups:86,registrations:61}];
function downloadCsv(rows,filename){const headers=Object.keys(rows[0]||{});const content=[headers.join(','),...rows.map(row=>headers.map(key=>`"${String(row[key]??'').replaceAll('"','""')}"`).join(','))].join('\n');const blob=new Blob([content],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=filename;link.click();URL.revokeObjectURL(url);}

export function AdminDashboard(){
  const {user}=useAuth();const toast=useToast();const isAdmin=user?.role==='ADMIN';const[events,setEvents]=useState([]);const[students,setStudents]=useState([]);const[analytics,setAnalytics]=useState(null);const[selectedEvent,setSelectedEvent]=useState('');const[registrations,setRegistrations]=useState([]);const[form,setForm]=useState(blank);const[editing,setEditing]=useState(null);const[saving,setSaving]=useState(false);const[loading,setLoading]=useState(true);const[query,setQuery]=useState('');
  useEffect(()=>{Promise.all([eventsApi.list(),studentsApi.list(),...(isAdmin?[adminApi.analytics()]:[])]).then(([e,s,a])=>{setEvents(e.data);setStudents(s.data);if(a)setAnalytics(a.data);if(e.data[0])setSelectedEvent(e.data[0].id);}).catch(()=>toast.error('Organizer data could not be loaded.')).finally(()=>setLoading(false));},[isAdmin]);
  useEffect(()=>{if(!selectedEvent)return;eventsApi.registrations(selectedEvent).then(({data})=>setRegistrations(data)).catch(()=>setRegistrations([]));},[selectedEvent]);
  const visibleStudents=useMemo(()=>students.filter(s=>s.lookingForTeam&&`${s.fullName} ${s.collegeName} ${s.major} ${s.skills.map(x=>x.skillName).join(' ')}`.toLowerCase().includes(query.toLowerCase())),[students,query]);
  const setField=(field,value)=>setForm(f=>({...f,[field]:value}));
  const edit=(event)=>{setEditing(event);setForm({...blank,...event,skills:(event.skills||[]).join(', ')});};
  const save=async(e)=>{e.preventDefault();if(!form.title.trim()||!form.date){toast.error('Add an event name and date first.');return;}setSaving(true);const payload={...form,skills:form.skills.split(',').map(s=>s.trim()).filter(Boolean)};try{const{data}=editing?await eventsApi.update(editing.id,payload):await eventsApi.create(payload);setEvents(current=>editing?current.map(item=>item.id===editing.id?data:item):[data,...current]);setSelectedEvent(data.id);setEditing(null);setForm(blank);toast.success(editing?'Event updated.':'Your event is live in the preview.');}catch{toast.error('Event could not be saved.');}finally{setSaving(false);}};
  const exportRegistrations=()=>{if(!registrations.length){toast.info('There are no registrations to export yet.');return;}downloadCsv(registrations.map(person=>({name:person.fullName,email:person.email,college:person.collegeName,major:person.major,skills:person.skills?.map(s=>s.skillName).join('; ')})),`${events.find(e=>e.id===selectedEvent)?.title?.replaceAll(' ','-')||'event'}-registrations.csv`);toast.success('Registration list downloaded as CSV.');};
  const rows=analytics?.signups?.map((signups,i)=>({day:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i],signups,registrations:analytics.registrations?.[i]||0}))||chartFallback;
  return <div className="mx-auto max-w-[1440px] space-y-7 pb-24 md:pb-10"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#898278]">Organizer and admin space</p><h1 className="editorial-title display-font mt-2 text-5xl font-extrabold sm:text-6xl">Make room for<br/><span className="editorial-italic normal-case">what’s next.</span></h1></div><Badge color="amber">{user?.role==='ADMIN'?'Admin':'Organizer'} studio</Badge></header>
    {isAdmin&&<section className="grid gap-4 sm:grid-cols-3">{[['Events',analytics?.events??events.length,'CalendarDays','sky'],['Students',analytics?.students??students.length,'Users','green'],['Teams',analytics?.teams??8,'Sparkles','coral']].map(([label,value,icon,tone],i)=><motion.div key={label} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:i*.05}}><Card color={['sky','sage','peach'][i]} className="flex items-center gap-4 p-5"><GradientIcon name={icon} tone={tone}/><div><p className="display-font text-3xl font-extrabold">{loading?'—':value}</p><p className="text-xs font-semibold">{label} in the community</p></div></Card></motion.div>)}</section>}
    {isAdmin&&<section className="grid gap-5 lg:grid-cols-2"><Card className="p-5"><h2 className="display-font font-extrabold">Community signups</h2><p className="mt-1 text-xs text-[#817b71]">New accounts over the last week</p><div className="mt-3 h-56"><ResponsiveContainer width="100%" height="100%"><LineChart data={rows}><CartesianGrid vertical={false} stroke="currentColor" opacity={.1}/><XAxis dataKey="day" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip/><Line type="monotone" dataKey="signups" stroke="#6f9b64" strokeWidth={3} dot={{r:3}}/></LineChart></ResponsiveContainer></div></Card><Card className="p-5"><h2 className="display-font font-extrabold">Event registrations</h2><p className="mt-1 text-xs text-[#817b71]">Registrations through this week</p><div className="mt-3 h-56"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows}><CartesianGrid vertical={false} stroke="currentColor" opacity={.1}/><XAxis dataKey="day" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip/><Bar dataKey="registrations" fill="#df9478" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></div></Card></section>}

    <section className="grid gap-5 xl:grid-cols-[1fr_350px]"><Card className="p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#898278]">Publish something worth showing up for</p><h2 className="display-font mt-2 text-xl font-extrabold">{editing?'Edit your event':'Create an event'}</h2></div>{editing&&<Button variant="quiet" onClick={()=>{setEditing(null);setForm(blank);}}><X size={15}/>Cancel edit</Button>}</div><div className="mt-5 grid gap-5 lg:grid-cols-[1fr_300px]"><form onSubmit={save} className="space-y-3"><Input label="Event name" value={form.title} onChange={e=>setField('title',e.target.value)} placeholder="A good name for a good challenge"/><div className="grid gap-3 sm:grid-cols-2"><Input label="Organizer" value={form.organizer} onChange={e=>setField('organizer',e.target.value)} placeholder="Your student group"/><label className="block text-sm font-semibold">Category<select value={form.category} onChange={e=>setField('category',e.target.value)} className="auth-input mt-2">{['Hackathon','Design sprint','Datathon','Sprint','Pitch challenge','CTF'].map(c=><option key={c}>{c}</option>)}</select></label><label className="block text-sm font-semibold">Scope<select value={form.scope} onChange={e=>setField('scope',e.target.value)} className="auth-input mt-2"><option>Inter-college</option><option>Intra-college</option></select></label><label className="block text-sm font-semibold">Mode<select value={form.mode} onChange={e=>setField('mode',e.target.value)} className="auth-input mt-2"><option>Hybrid</option><option>In person</option><option>Online</option></select></label><Input label="Event date" type="date" value={form.date} onChange={e=>setField('date',e.target.value)}/><Input label="Registration deadline" type="date" value={form.deadline} onChange={e=>setField('deadline',e.target.value)}/><Input label="Team size" value={form.teamSize} onChange={e=>setField('teamSize',e.target.value)} placeholder="2–4"/><Input label="Required skills (comma-separated)" value={form.skills} onChange={e=>setField('skills',e.target.value)} placeholder="React, Python, Figma"/></div><label className="block text-sm font-semibold">Event description<textarea rows="3" value={form.description} onChange={e=>setField('description',e.target.value)} className="auth-input mt-2 resize-y font-normal" placeholder="Describe the challenge and what students can expect."/></label><Button type="submit" disabled={saving} showArrow><Save size={15}/>{saving?'Saving…':editing?'Save event':'Publish event'}</Button></form>
      <Card color={form.color||'sage'} className="h-fit overflow-hidden p-4"><p className="text-[10px] font-bold uppercase tracking-[.17em] text-[#898278]">Live event preview</p><div className="my-4 flex h-28 items-center justify-between rounded-2xl bg-white/45 p-4 dark:bg-black/10"><GradientIcon name="CalendarDays" tone="coral" tileSize={52} size={23}/><Badge>{form.scope}</Badge></div><Badge color="sky">{form.category}</Badge><h3 className="display-font mt-3 text-xl font-extrabold">{form.title||'Your event name'}</h3><p className="mt-2 line-clamp-3 text-xs leading-5 text-[#6b665e] dark:text-[#c8c1b6]">{form.description||'Add a short description to invite students into the idea.'}</p><div className="mt-4 flex gap-2"><Badge>{form.date}</Badge><Badge color="ink">{form.mode}</Badge></div><div className="mt-3 flex flex-wrap gap-1.5">{form.skills.split(',').map(s=>s.trim()).filter(Boolean).map(s=><SkillChip key={s}>{s}</SkillChip>)}</div></Card></div></Card>
      <div className="space-y-5"><Card className="p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#898278]">Who's coming along?</p><h2 className="display-font mt-1 font-extrabold">Registrations</h2></div><Button variant="secondary" className="!px-3 !py-2 !text-[11px]" onClick={exportRegistrations}><Download size={14}/>Export CSV</Button></div><select aria-label="Select event registrations" value={selectedEvent} onChange={e=>setSelectedEvent(e.target.value)} className="auth-input mt-4">{events.map(event=><option key={event.id} value={event.id}>{event.title}</option>)}</select><div className="mt-3 space-y-2">{registrations.slice(0,4).map(person=><div key={person.id} className="flex items-center gap-2 rounded-xl bg-[#F6F3EE] p-2 dark:bg-white/5"><Avatar src={person.avatarUrl} name={person.fullName} size={31}/><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-bold">{person.fullName}</p><p className="truncate text-[9px] text-[#898278]">{person.collegeName}</p></div></div>)}{registrations.length===0&&<p className="py-3 text-xs text-[#898278]">No registrations to show for this event yet.</p>}</div><p className="mt-3 text-[10px] text-[#898278]">{registrations.length} registrations · {events.find(e=>e.id===selectedEvent)?.title}</p></Card><Card color="peach" className="p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#8b6957] dark:text-[#e1c1ae]">Ready to meet a crew</p><h2 className="display-font mt-1 font-extrabold">Looking for teammates</h2></div><Badge color="pink">{visibleStudents.length}</Badge></div><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search students looking for a team" placeholder="Search a skill or name" className="auth-input mt-4 !bg-white/75"/><div className="mt-3 space-y-2">{loading?[0,1,2].map(i=><TableRowSkeleton key={i}/>):visibleStudents.slice(0,4).map(person=><div key={person.id} className="flex items-center gap-2 rounded-xl bg-white/70 p-2 dark:bg-black/10"><Avatar src={person.avatarUrl} name={person.fullName} size={31}/><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-bold">{person.fullName}</p><p className="truncate text-[9px] text-[#777269]">{person.skills.slice(0,2).map(s=>s.skillName).join(' · ')}</p></div><Badge color="green">Open</Badge></div>)}</div></Card></div>
    </section>
    <section><div className="mb-4"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#898278]">Your event board</p><h2 className="display-font mt-1 text-xl font-extrabold">Current events</h2></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{events.map((event,i)=><Card key={event.id} color={event.color||['sage','peach','sky'][i%3]} className="flex items-center gap-3 p-4"><GradientIcon name="CalendarDays" tone={['green','coral','sky'][i%3]} tileSize={40} size={17}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{event.title}</p><p className="text-[10px] text-[#777269]">{event.date} · {event.registrations||0} registered</p></div><Button variant="secondary" className="!px-3 !py-2 !text-[11px]" onClick={()=>edit(event)}>Edit</Button></Card>)}</div></section>
  </div>;
}
