import React,{useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUp,BrainCircuit,ChevronDown,MessageCircle,Minimize2,Sparkles,Users,X} from 'lucide-react';
import {motion,AnimatePresence} from 'framer-motion';
import {assistantApi} from '../api/client';
import {students} from '../api/mockData';
import {Avatar,Badge,Button,Card,ProgressRing,SkillChip} from '../components/ui';
import {GradientIcon} from '../components/GradientIcon';

const prompts=['I need a Python developer','What skills are missing from my team?','Find an event for designers'];
const welcome={id:'welcome',role:'assistant',text:'Hi! I’m here to help you find your people. Tell me what you’re building or what kind of teammate you need.'};
function MatchCards({items=[]}){return <div className="mt-3 grid gap-2">{items.slice(0,3).map((person,i)=><Card key={person.id} color={['sage','sky','peach'][i%3]} className="p-3"><div className="flex items-center gap-3"><Avatar src={person.avatarUrl} name={person.fullName} size={40}/><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{person.fullName}</p><p className="truncate text-[10px] text-[#777269]">{person.major}</p></div><ProgressRing value={person.matchScore||88} size={40} stroke={3}/></div><div className="mt-2 flex flex-wrap gap-1.5">{(person.matchingSkills||person.skills?.slice(0,2).map(s=>s.skillName)||[]).map(skill=><SkillChip key={skill} tone="green">{skill}</SkillChip>)}</div><p className="mt-2 text-[10px] leading-4 text-[#625e56] dark:text-[#d0c9be]">{person.aiReason||'A thoughtful skills match for the kind of team you are building.'}</p><Link to={`/students/${person.id}`} className="mt-2 inline-flex items-center gap-1 text-[10px] font-bold">See profile <ChevronDown size={12} className="-rotate-90"/></Link></Card>)}</div>;}
function MessageList({messages,typing=false}){const listRef=useRef(null);useEffect(()=>{if(listRef.current)listRef.current.scrollTop=listRef.current.scrollHeight;},[messages,typing]);return <div ref={listRef} className="flex-1 space-y-4 overflow-y-auto px-4 py-5">{messages.map((message)=><div key={message.id} className={`flex gap-2.5 ${message.role==='user'?'justify-end':''}`}>{message.role==='assistant'&&<GradientIcon name="Sparkles" tone="pink" tileSize={30} size={14}/>}<div className={`max-w-[86%] ${message.role==='user'?'rounded-[20px] rounded-br-md bg-[#141414] px-4 py-3 text-white dark:bg-white dark:text-[#141414]':'rounded-[20px] rounded-tl-md bg-white/90 px-4 py-3 text-[#33312d] dark:bg-white/10 dark:text-[#f5f1e9]'}`}><p className="whitespace-pre-wrap text-xs leading-5">{message.text}</p>{message.recommendations?.length>0&&<MatchCards items={message.recommendations}/>}</div></div>)}{typing&&<div className="flex items-center gap-3"><GradientIcon name="Sparkles" tone="pink" tileSize={30} size={14}/><div aria-label="Assistant is thinking" className="flex gap-1 rounded-full bg-white px-4 py-3 dark:bg-white/10"><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-[#df7188]"/><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-[#df7188] [animation-delay:120ms]"/><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-[#df7188] [animation-delay:240ms]"/></div></div>}</div>;}

export function Assistant(){
  const[messages,setMessages]=useState([welcome]);const[text,setText]=useState('');const[busy,setBusy]=useState(false);const input=useRef(null);
  const send=async(value=text)=>{const content=value.trim();if(!content||busy)return;setText('');setMessages(old=>[...old,{id:`user-${Date.now()}`,role:'user',text:content}]);setBusy(true);try{const {data}=await assistantApi.chat({message:content});const words=(data.reply||'I’m thinking through a few good next steps for you.').split(' ');let answer='';const id=`assistant-${Date.now()}`;setMessages(old=>[...old,{id,role:'assistant',text:''}]);for(const word of words){answer+=`${answer?' ':''}${word}`;setMessages(old=>old.map(message=>message.id===id?{...message,text:answer}:message));await new Promise(resolve=>window.setTimeout(resolve,22));}setMessages(old=>old.map(message=>message.id===id?{...message,recommendations:data.recommendations||[]}:message));}catch{setMessages(old=>[...old,{id:`assistant-${Date.now()}`,role:'assistant',text:'I couldn’t reach the assistant just now. Try again in a moment.'}]);}finally{setBusy(false);}};
  return <div className="mx-auto grid max-w-6xl gap-6 pb-24 md:min-h-[calc(100vh-150px)] md:grid-cols-[1fr_270px] md:pb-6"><section className="flex min-h-[68vh] flex-col overflow-hidden rounded-[30px] bg-[#FBEEC3] dark:bg-[#403b2a]"><header className="flex items-center gap-3 border-b border-black/[.06] p-5 dark:border-white/[.08]"><GradientIcon name="BrainCircuit" tone="pink" tileSize={44} size={21}/><div className="min-w-0 flex-1"><h1 className="display-font text-base font-extrabold">SkillSync sidekick</h1><p className="text-[10px] text-[#776c51] dark:text-[#d7ca9f]">Ready to find your next teammate</p></div><Badge color="green">AI assistant</Badge></header><MessageList messages={messages} typing={busy}/><div className="border-t border-black/[.06] p-4 dark:border-white/[.08]"><div className="mb-3 flex flex-wrap gap-2">{prompts.map(prompt=><button key={prompt} disabled={busy} onClick={()=>send(prompt)} className="rounded-full bg-white/75 px-3 py-2 text-[10px] font-semibold hover:bg-white dark:bg-white/10 dark:hover:bg-white/15">{prompt}</button>)}</div><form onSubmit={e=>{e.preventDefault();send();}} className="flex items-center gap-2 rounded-full bg-white p-2 pl-4 dark:bg-[#24221e]"><input ref={input} value={text} onChange={e=>setText(e.target.value)} disabled={busy} placeholder="Tell me what you’re looking for…" aria-label="Message the assistant" className="min-w-0 flex-1 bg-transparent text-xs outline-none placeholder:text-[#928b81]"/><button type="submit" disabled={!text.trim()||busy} aria-label="Send message" className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#141414] text-white disabled:opacity-35 dark:bg-white dark:text-[#141414]"><ArrowUp size={18}/></button></form></div></section>
    <aside className="space-y-4"><Card className="p-5"><div className="flex items-center gap-3"><GradientIcon name="Sparkles" tone="amber" tileSize={40} size={17}/><h2 className="display-font font-extrabold">Try a prompt</h2></div><div className="mt-4 space-y-2">{prompts.map((p,i)=><button key={p} onClick={()=>send(p)} disabled={busy} className="flex w-full items-start gap-2 rounded-2xl bg-[#F6F3EE] p-3 text-left text-xs font-semibold leading-5 hover:bg-[#ebe7df] dark:bg-white/5 dark:hover:bg-white/10"><span className="text-[#a47a3c]">0{i+1}</span>{p}</button>)}</div></Card><Card color="sky" className="p-5"><h2 className="display-font font-extrabold">A good team has range.</h2><p className="mt-2 text-xs leading-5 text-[#5b6770] dark:text-[#d0dce1]">Ask which skills your team already has, then find the strengths that round it out.</p><div className="mt-4 flex -space-x-2">{students.slice(1,5).map(s=><Avatar key={s.id} src={s.avatarUrl} name={s.fullName} size={34} className="border-2 border-[#D8E8F4] dark:border-[#29363d]"/>)}</div></Card></aside>
  </div>;
}

export function AssistantWidget(){
  const[open,setOpen]=useState(false);const[messages,setMessages]=useState([welcome]);const[text,setText]=useState('');const[busy,setBusy]=useState(false);
  const send=async(value=text)=>{const content=value.trim();if(!content||busy)return;setText('');setMessages(old=>[...old,{id:`widget-user-${Date.now()}`,role:'user',text:content}]);setBusy(true);try{const {data}=await assistantApi.chat({message:content});setMessages(old=>[...old,{id:`widget-assistant-${Date.now()}`,role:'assistant',text:data.reply,recommendations:data.recommendations||[]}]);}catch{setMessages(old=>[...old,{id:`widget-assistant-${Date.now()}`,role:'assistant',text:'I’m having trouble connecting just now. Try again soon.'}]);}finally{setBusy(false);}};
  return <div className="fixed bottom-[88px] right-4 z-[80] flex flex-col items-end gap-3 md:bottom-6 md:right-6"><AnimatePresence>{open&&<motion.section initial={{opacity:0,y:14,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:10,scale:.98}} className="flex h-[min(72vh,560px)] w-[min(390px,calc(100vw-2rem))] flex-col overflow-hidden rounded-[26px] border border-black/5 bg-[#F6F3EE] shadow-2xl dark:border-white/10 dark:bg-[#24221e]"><header className="flex items-center gap-2 border-b border-black/5 p-3 dark:border-white/10"><GradientIcon name="Sparkles" tone="pink" tileSize={36} size={16}/><div className="min-w-0 flex-1"><p className="text-xs font-extrabold">SkillSync sidekick</p><p className="text-[10px] text-[#888176]">Here to help</p></div><Link to="/assistant" onClick={()=>setOpen(false)} aria-label="Open full assistant" className="rounded-full p-2 hover:bg-black/5 dark:hover:bg-white/10"><MessageCircle size={15}/></Link><button onClick={()=>setOpen(false)} aria-label="Minimize assistant" className="rounded-full p-2 hover:bg-black/5 dark:hover:bg-white/10"><Minimize2 size={15}/></button></header><MessageList messages={messages} typing={busy}/><div className="border-t border-black/5 p-3 dark:border-white/10"><div className="mb-2 flex gap-1.5 overflow-x-auto">{prompts.slice(0,2).map(p=><button key={p} onClick={()=>send(p)} className="shrink-0 rounded-full bg-white px-2.5 py-1.5 text-[9px] font-semibold dark:bg-white/10">{p}</button>)}</div><form onSubmit={e=>{e.preventDefault();send();}} className="flex items-center gap-2 rounded-full bg-white p-1.5 pl-4 dark:bg-white/10"><input value={text} onChange={e=>setText(e.target.value)} aria-label="Ask SkillSync" placeholder="Ask a question…" className="min-w-0 flex-1 bg-transparent text-xs outline-none"/><button disabled={!text.trim()||busy} aria-label="Send" className="grid h-8 w-8 place-items-center rounded-full bg-[#141414] text-white disabled:opacity-35 dark:bg-white dark:text-[#141414]"><ArrowUp size={15}/></button></form></div></motion.section>}</AnimatePresence><button onClick={()=>setOpen(v=>!v)} aria-label={open?'Close SkillSync assistant':'Open SkillSync assistant'} aria-expanded={open} className="group grid h-14 w-14 place-items-center rounded-full bg-[#141414] text-white shadow-lg transition-transform hover:scale-105 dark:bg-white dark:text-[#141414]"><AnimatePresence mode="wait"><motion.span key={open?'close':'open'} initial={{opacity:0,rotate:-35,scale:.8}} animate={{opacity:1,rotate:0,scale:1}} exit={{opacity:0,rotate:35,scale:.8}}>{open?<X size={22}/>:<Sparkles size={22}/>}</motion.span></AnimatePresence></button></div>;
}
