import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, Eye, Sparkles, CalendarDays, Users, Mail, TrendingUp, MapPin, Clock3 } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useAuth } from '../context/AuthContext';
import { eventsApi, invitesApi, teamsApi, studentsApi } from '../api/client';
import { students as mockStudents } from '../api/mockData';
import { Avatar } from '../components/ui';
import { GradientIcon } from '../components/GradientIcon';
import { Card, Badge, Button, ProgressRing, SkillChip } from '../components/ui';
import { CardSkeleton } from '../components/Skeleton';

const activity=[{day:'Mon',matches:2,views:8},{day:'Tue',matches:4,views:12},{day:'Wed',matches:3,views:10},{day:'Thu',matches:6,views:18},{day:'Fri',matches:5,views:16},{day:'Sat',matches:8,views:22},{day:'Sun',matches:7,views:25}];
const dateLabel=(date)=>new Intl.DateTimeFormat('en',{month:'short',day:'numeric'}).format(new Date(`${date}T12:00:00`));
const tones=['sage','peach','sky','butter'];

export function Dashboard(){
  const {user}=useAuth(); const [events,setEvents]=useState([]);const [teams,setTeams]=useState([]);const [invites,setInvites]=useState([]);const [people,setPeople]=useState([]);const [loading,setLoading]=useState(true);
  useEffect(()=>{let mounted=true;Promise.all([eventsApi.list(),teamsApi.mine(),invitesApi.mine(),studentsApi.list()]).then(([e,t,i,s])=>{if(!mounted)return;setEvents(e.data);setTeams(t.data);setInvites(i.data.filter(x=>x.status==='pending'));setPeople(s.data.filter(x=>x.id!==user?.id&&x.lookingForTeam).slice(0,6));}).catch(()=>{}).finally(()=>mounted&&setLoading(false));return()=>{mounted=false;};},[user?.id]);
  const name=user?.fullName?.split(' ')[0]||'friend';const completeness=user?.profileCompleteness||65;
  const stats=[['Upcoming events',events.length,'Keep an eye on the calendar','CalendarDays','sky','/events'],['Active teams',teams.length,'Ideas in progress','Users','green','/teams'],['Pending invites',invites.length,'A new hello awaits','Mail','coral','/teams'],['Profile views','24','↑ 18% this week','Eye','amber','/profile']];
  const recs=people.length?people:mockStudents.slice(1,7);
  return <div className="mx-auto max-w-[1440px] space-y-8 pb-24 md:pb-10">
    <motion.section initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="relative overflow-hidden rounded-[32px] bg-[#DCE8D6] p-6 dark:bg-[#303a2d] sm:p-9"><div className="relative z-10 max-w-3xl"><Badge color="green">Your week, in good company</Badge><h1 className="editorial-title display-font mt-5 text-5xl font-extrabold sm:text-7xl">Hi {name},<br/><span className="editorial-italic normal-case">what will you make?</span></h1><p className="mt-5 max-w-xl leading-7 text-[#596451] dark:text-[#d1dbcb]">There are new events to explore and teammates who might be just right for your next idea.</p><Link to="/teams/create" className="mt-6 inline-flex"><Button showArrow>Start forming a team</Button></Link></div><div className="absolute -right-10 -top-20 h-72 w-72 rounded-full bg-[#FBEEC3] opacity-75 blur-3xl"/><div className="absolute bottom-0 right-[12%] hidden translate-y-1/3 rotate-12 rounded-t-[40px] bg-[#FBE1D0] p-8 sm:block"><GradientIcon name="Sparkles" tone="coral" tileSize={86} size={40}/></div></motion.section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label,value,caption,icon,tone,path],index)=><motion.div key={label} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:index*.05}}><Link to={path} className="block h-full"><Card color={tones[index]} className="flex h-full min-h-[170px] flex-col justify-between p-5 transition-transform hover:-translate-y-1"><div className="flex items-start justify-between"><GradientIcon name={icon} tone={tone} tileSize={46} size={21}/><ArrowRight size={16} className="mt-2 opacity-45"/></div><div><p className="display-font text-4xl font-extrabold tracking-tight">{loading?'—':value}</p><p className="mt-1 text-sm font-bold">{label}</p><p className="mt-1 text-xs text-[#6b665e] dark:text-[#c8c1b6]">{caption}</p></div></Card></Link></motion.div>)}</section>

    <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]">
      <section className="rounded-[28px] bg-white/75 p-6 panel-shadow dark:bg-white/[.06] sm:p-7"><div className="mb-5 flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.17em] text-[#898278]">A little momentum</p><h2 className="display-font mt-2 text-xl font-extrabold">Your activity this week</h2></div><Badge color="green"><TrendingUp size={13} className="mr-1"/> On the rise</Badge></div><div className="h-[230px] w-full" role="img" aria-label="Weekly profile views and teammate matches chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={activity} margin={{top:8,right:8,left:-24,bottom:0}}><defs><linearGradient id="viewsFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#74a36b" stopOpacity={.3}/><stop offset="95%" stopColor="#74a36b" stopOpacity={0}/></linearGradient><linearGradient id="matchesFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#df8c70" stopOpacity={.22}/><stop offset="95%" stopColor="#df8c70" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="currentColor" opacity={.09}/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fontSize:11,fill:'#817b71'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#817b71'}}/><Tooltip contentStyle={{borderRadius:14,border:0,boxShadow:'0 8px 24px rgba(0,0,0,.12)'}}/><Area type="monotone" dataKey="views" name="Profile views" stroke="#6f9b64" fill="url(#viewsFill)" strokeWidth={2.5}/><Area type="monotone" dataKey="matches" name="New matches" stroke="#df8c70" fill="url(#matchesFill)" strokeWidth={2.5}/></AreaChart></ResponsiveContainer></div><div className="mt-3 flex gap-5 text-xs text-[#777269]"><span><i className="mr-2 inline-block h-2 w-2 rounded-full bg-[#6f9b64]"/>Profile views</span><span><i className="mr-2 inline-block h-2 w-2 rounded-full bg-[#df8c70]"/>Matches</span></div></section>
      <section className="rounded-[28px] bg-white/75 p-6 panel-shadow dark:bg-white/[.06] sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.17em] text-[#898278]">One small upgrade</p><h2 className="display-font mt-2 text-xl font-extrabold">Your profile</h2></div><ProgressRing value={completeness} label={`Profile ${completeness}% complete`}/></div><p className="mt-5 text-sm leading-6 text-[#6a655d] dark:text-[#c9c2b8]">A few more details help teammates get to know your style and strengths.</p><div className="mt-4 space-y-2.5 text-xs">{[{label:'Add three or more skills',done:(user?.skills?.length||0)>=3},{label:'Share a project link',done:!!(user?.githubUrl||user?.portfolioUrl)},{label:'Write a quick intro',done:!!user?.bio}].map(t=><div key={t.label} className="flex items-center gap-2"><span className={`grid h-4 w-4 place-items-center rounded-full ${t.done?'bg-[#dce8d6] text-[#446d41]':'border border-[#c8c1b6]'}`}>{t.done?'✓':''}</span><span className={t.done?'text-[#868076] line-through':'font-semibold'}>{t.label}</span></div>)}</div><Link to="/profile" className="mt-5 inline-flex items-center gap-2 text-sm font-bold">Tune your profile <ArrowRight size={15}/></Link></section>
    </div>

    <section><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.17em] text-[#898278]">Complementary skills, shared ambition</p><h2 className="display-font mt-2 text-2xl font-extrabold tracking-tight">People you might click with</h2></div><Link to="/students" className="hidden items-center gap-2 text-sm font-bold sm:flex">See everyone <ArrowRight size={15}/></Link></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{recs.slice(0,3).map((person,i)=><Card key={person.id} color={tones[(i+1)%tones.length]} className="p-5"><div className="flex items-center gap-3"><Avatar src={person.avatarUrl} name={person.fullName} size={52}/><div className="min-w-0 flex-1"><h3 className="truncate font-bold">{person.fullName}</h3><p className="truncate text-xs text-[#6b665e] dark:text-[#c8c1b6]">{person.major} · {person.collegeName}</p></div><ProgressRing size={48} stroke={4} value={92-i*6} label={`${92-i*6}% match`}/></div><div className="mt-4 flex flex-wrap gap-2">{(person.skills||[]).slice(0,3).map(skill=><SkillChip key={skill.id||skill.skillName} tone={i%2?'amber':'sky'}>{skill.skillName}</SkillChip>)}</div><p className="mt-4 text-xs leading-5 text-[#69645c] dark:text-[#d0c9be]">Their skills complement your frontend experience. A good fit for a balanced team.</p><Link to="/assistant" className="mt-4 inline-flex items-center gap-2 text-xs font-bold">Explore match <ArrowRight size={14}/></Link></Card>)}</div></section>

    <section><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.17em] text-[#898278]">Worth putting on your calendar</p><h2 className="display-font mt-2 text-2xl font-extrabold tracking-tight">Upcoming events</h2></div><Link to="/events" className="inline-flex items-center gap-2 text-sm font-bold">Browse all <ArrowRight size={15}/></Link></div>{loading?<div className="grid gap-4 md:grid-cols-3"><CardSkeleton/><CardSkeleton/><CardSkeleton/></div>:<div className="grid gap-4 md:grid-cols-3">{events.slice(0,3).map((event,i)=><Card key={event.id} color={event.color||tones[i]} className="p-5"><div className="flex items-center justify-between"><Badge>{event.category}</Badge><span className="text-xs font-bold">{dateLabel(event.date)}</span></div><h3 className="display-font mt-6 text-xl font-extrabold">{event.title}</h3><div className="mt-3 flex flex-wrap gap-3 text-xs text-[#706b63] dark:text-[#c9c2b8]"><span className="inline-flex items-center gap-1"><MapPin size={13}/>{event.mode||'Hybrid'}</span><span className="inline-flex items-center gap-1"><Clock3 size={13}/>{event.teamSize||'2–4'} people</span></div><div className="mt-4 flex flex-wrap gap-2">{(event.skills||[]).slice(0,3).map(skill=><SkillChip key={skill}>{skill}</SkillChip>)}</div></Card>)}</div>}</section>
  </div>;
}

