import React,{useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {ArrowLeft,ArrowRight,CalendarDays,MapPin,Users,Check,Clock3} from 'lucide-react';
import {motion} from 'framer-motion';
import {eventsApi,teamsApi,studentsApi} from '../api/client';
import {useToast} from '../context/ToastContext';
import {Avatar,Badge,Button,Card,Modal,Tabs,SkillChip} from '../components/ui';
import {GradientIcon} from '../components/GradientIcon';
import {triggerConfetti} from '../components/Confetti';

export function EventDetail(){
  const {id}=useParams();const[ev,setEv]=useState(null);const[teams,setTeams]=useState([]);const[people,setPeople]=useState([]);const[tab,setTab]=useState('overview');const[modal,setModal]=useState(false);const[status,setStatus]=useState('Looking for a team');const[registered,setRegistered]=useState(false);const toast=useToast();
  useEffect(()=>{Promise.all([eventsApi.byId(id),teamsApi.mine(),studentsApi.list()]).then(([event,teamRes,studentRes])=>{setEv(event.data);setTeams(teamRes.data);setPeople(studentRes.data.slice(0,8));}).catch(()=>toast.error('Event details could not be loaded.'));},[id]);
  const join=async()=>{if(!ev)return;setRegistered(true);setModal(false);triggerConfetti();toast.success(`You're on the list for ${ev.title}.`);try{await eventsApi.register(id,{status});}catch{setRegistered(false);toast.error('Registration could not be saved.');}};
  if(!ev)return <div className="mx-auto max-w-5xl space-y-5"><div className="h-12 w-48 animate-pulse rounded-2xl bg-black/5 dark:bg-white/10"/><div className="h-72 animate-pulse rounded-3xl bg-black/5 dark:bg-white/10"/></div>;
  const tabs=[{value:'overview',label:'Overview'},{value:'requirements',label:'Requirements'},{value:'teams',label:`Teams (${teams.filter(t=>t.eventId===id).length})`},{value:'participants',label:'Participants'}];
  return <div className="mx-auto max-w-5xl space-y-6 pb-24 md:pb-10"><Link to="/events" className="inline-flex items-center gap-2 text-sm font-semibold text-[#777269]"><ArrowLeft size={15}/> All events</Link><Card color={ev.color||'sage'} className="relative overflow-hidden p-6 sm:p-9"><div className="absolute -right-8 -top-12 opacity-25"><GradientIcon name="Sparkles" tone="amber" tileSize={180} size={80}/></div><div className="relative z-[1] max-w-2xl"><div className="flex flex-wrap gap-2"><Badge>{ev.scope}</Badge><Badge color="ink">{ev.category}</Badge></div><h1 className="editorial-title display-font mt-6 text-5xl font-extrabold sm:text-7xl">{ev.title}</h1><p className="mt-5 max-w-xl leading-7 text-[#625e56] dark:text-[#d0c9be]">{ev.description}</p><div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-[#6c675f] dark:text-[#cbc4b9]"><span className="inline-flex items-center gap-1.5"><CalendarDays size={14}/>{ev.date}</span><span className="inline-flex items-center gap-1.5"><MapPin size={14}/>{ev.mode}</span><span className="inline-flex items-center gap-1.5"><Users size={14}/>{ev.teamSize} people per team</span></div><Button onClick={()=>setModal(true)} disabled={registered} className="mt-6" showArrow>{registered?'You’re registered':'Register for event'}</Button></div></Card>
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><Tabs items={tabs} value={tab} onChange={setTab} label="Event details"/><span className="inline-flex items-center gap-2 text-xs text-[#777269]"><Clock3 size={14}/> Registration closes {ev.deadline||'soon'}</span></div>
    <motion.div key={tab} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="grid gap-5 lg:grid-cols-[1fr_270px]">
      {tab==='overview'&&<Card className="p-6"><h2 className="display-font text-xl font-extrabold">A weekend to make something matter</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-[#625e56] dark:text-[#d0c9be]">{ev.description} Teams will have room to try new things, learn from mentors, and present what they’ve made. Bring your curiosity and a willingness to work together.</p><h3 className="mt-7 font-bold">Hosted by {ev.organizer}</h3><p className="mt-2 text-xs text-[#777269]">Expect good people, practical challenges, and enough time to make your idea real.</p></Card>}
      {tab==='requirements'&&<Card className="p-6"><h2 className="display-font text-xl font-extrabold">Skills that help you get started</h2><p className="mt-2 text-sm text-[#706b63] dark:text-[#cbc4b9]">Every team is different. These skills are helpful, and learning together is part of the point.</p><div className="mt-5 flex flex-wrap gap-2">{ev.skills.map((s,i)=><SkillChip key={s} tone={['sky','green','pink','amber','coral'][i%5]}>{s}</SkillChip>)}</div><div className="mt-8 rounded-2xl bg-[#DCE8D6] p-4 text-sm leading-6 text-[#52604d] dark:bg-[#303a2d] dark:text-[#d1dbcb]">You don’t need to tick every box. Balanced teams often bring a mix of technical and creative strengths.</div></Card>}
      {tab==='teams'&&<Card className="p-6"><div className="flex items-center justify-between"><div><h2 className="display-font text-xl font-extrabold">Teams looking for a teammate</h2><p className="mt-1 text-xs text-[#777269]">Meet people already getting their ideas together.</p></div><Link to="/teams/create"><Button className="!px-4 !py-2 !text-xs">Start a team</Button></Link></div><div className="mt-5 space-y-3">{teams.filter(t=>t.eventId===id).length?teams.filter(t=>t.eventId===id).map(t=><div key={t.id} className="flex items-center gap-3 rounded-2xl bg-[#F6F3EE] p-4 dark:bg-white/5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#FBE1D0]"><Users size={18}/></span><div className="min-w-0 flex-1"><p className="font-bold">{t.name}</p><p className="text-xs text-[#777269]">{t.project||'New idea'} · {t.memberIds.length} members</p></div><Badge color="green">{t.status}</Badge></div>):<p className="rounded-2xl bg-[#F6F3EE] p-5 text-sm dark:bg-white/5">You could be the first team here. Start your own and find your people.</p>}</div></Card>}
      {tab==='participants'&&<Card className="p-6"><h2 className="display-font text-xl font-extrabold">A few students going</h2><p className="mt-2 text-xs text-[#777269]">There are {ev.registrations} curious makers on the list.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{people.slice(0,6).map((p,i)=><div key={p.id} className="flex items-center gap-3 rounded-2xl bg-[#F6F3EE] p-3 dark:bg-white/5"><Avatar src={p.avatarUrl} name={p.fullName} size={42}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{p.fullName}</p><p className="truncate text-xs text-[#777269]">{p.major}</p></div>{i<3&&<Check size={15} className="text-[#6f9b64]"/>}</div>)}</div></Card>}
      <Card color="butter" className="h-fit p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#71674f]">The quick facts</p><div className="mt-4 space-y-4 text-sm"><div><p className="text-[11px] text-[#7f7661]">Date</p><p className="font-bold">{ev.date}</p></div><div><p className="text-[11px] text-[#7f7661]">Format</p><p className="font-bold">{ev.mode}</p></div><div><p className="text-[11px] text-[#7f7661]">Team size</p><p className="font-bold">{ev.teamSize} students</p></div><div><p className="text-[11px] text-[#7f7661]">Interested students</p><p className="font-bold">{ev.registrations}</p></div></div><Link to="/assistant" className="mt-5 flex items-center gap-2 text-xs font-bold">Find complementary skills <ArrowRight size={13}/></Link></Card>
    </motion.div>
    <Modal open={modal} title="A spot with your name on it" onClose={()=>setModal(false)}><div className="rounded-2xl bg-[#DCE8D6] p-4 dark:bg-[#303a2d]"><p className="text-xs font-bold uppercase tracking-wider">{ev.category}</p><h3 className="display-font mt-1 font-extrabold">{ev.title}</h3><p className="mt-1 text-xs">{ev.date} · teams of {ev.teamSize}</p></div><fieldset className="mt-5 space-y-2"><legend className="mb-2 text-sm font-bold">How are you joining?</legend>{['Looking for a team','Already have a team','Going solo'].map(x=><label key={x} className="flex items-center gap-3 rounded-2xl bg-white p-3 text-sm dark:bg-white/5"><input type="radio" name="registrationStatus" checked={status===x} onChange={()=>setStatus(x)} className="accent-[#6f9b64]"/>{x}</label>)}</fieldset><div className="mt-5 flex justify-end"><Button onClick={join} showArrow>Confirm registration</Button></div></Modal>
  </div>;
}

