import React,{useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {motion} from 'framer-motion';
import {ArrowRight,CalendarDays,Clock3,Grid2X2,List,MapPin,Search,Users} from 'lucide-react';
import {eventsApi} from '../api/client';
import {useToast} from '../context/ToastContext';
import {Button,Badge,Card,Modal} from '../components/ui';
import {GradientIcon} from '../components/GradientIcon';
import {SkillChip} from '../components/ui';
import {EmptyState} from '../components/EmptyState';
import {CardSkeleton} from '../components/Skeleton';
import {triggerConfetti} from '../components/Confetti';

const tones=['sage','peach','sky','butter','blush'];
export function Events(){
  const [allEvents,setAllEvents]=useState([]);const[loading,setLoading]=useState(true);const[query,setQuery]=useState('');const[scope,setScope]=useState('All events');const[skill,setSkill]=useState('Any skill');const[teamSize,setTeamSize]=useState('Any size');const[mode,setMode]=useState('grid');const[registering,setRegistering]=useState(null);const[registerMode,setRegisterMode]=useState('Looking for a team');const[registered,setRegistered]=useState({});const toast=useToast();
  useEffect(()=>{eventsApi.list().then(r=>setAllEvents(r.data)).catch(()=>toast.error('Events could not be loaded. Try again later.')).finally(()=>setLoading(false));},[]);
  const skills=useMemo(()=>['Any skill',[...new Set(allEvents.flatMap(e=>e.skills||[]))].sort()], [allEvents]);
  const teamSizes=useMemo(()=>[...new Set(allEvents.map(e=>e.teamSize).filter(Boolean))],[allEvents]);
  const filtered=useMemo(()=>allEvents.filter(e=>{const q=query.toLowerCase();return(!q||`${e.title} ${e.description} ${e.organizer} ${(e.skills||[]).join(' ')}`.toLowerCase().includes(q))&&(scope==='All events'||e.scope===scope)&&(skill==='Any skill'||e.skills?.includes(skill))&&(teamSize==='Any size'||e.teamSize===teamSize);}),[allEvents,query,scope,skill,teamSize]);
  const handleRegister=async()=>{if(!registering)return;setRegistered(s=>({...s,[registering.id]:true}));const event=registering;setRegistering(null);triggerConfetti();toast.success(`You're registered for ${event.title}.`);try{await eventsApi.register(event.id,{status:registerMode});}catch{setRegistered(s=>({...s,[event.id]:false}));toast.error('Registration could not be saved.');}};
  const scopeOptions=['All events','Inter-college','Intra-college'];
  return <div className="mx-auto max-w-[1440px] space-y-7 pb-24 md:pb-10"><header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#898278]">A good reason to clear your weekend</p><h1 className="editorial-title display-font mt-2 text-5xl font-extrabold sm:text-6xl">Find your<br/><span className="editorial-italic normal-case">next challenge.</span></h1></div><Badge color="sky"><CalendarDays size={14} className="mr-1.5"/>{allEvents.length} events to explore</Badge></header>
    <Card className="p-4 sm:p-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-[1fr_190px_190px_160px_auto]"><label className="relative sm:col-span-2 xl:col-span-1"><Search size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#888176]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search events, skills, organizers" className="auth-input pl-11" aria-label="Search events"/></label><select aria-label="Filter by college scope" value={scope} onChange={e=>setScope(e.target.value)} className="auth-input">{scopeOptions.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter by required skill" value={skill} onChange={e=>setSkill(e.target.value)} className="auth-input">{skills.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter by team size" value={teamSize} onChange={e=>setTeamSize(e.target.value)} className="auth-input"><option>Any size</option>{teamSizes.map(size=><option key={size}>{size}</option>)}</select><div className="flex items-center justify-end gap-1 rounded-full bg-[#F6F3EE] p-1 dark:bg-white/5"><button onClick={()=>setMode('grid')} aria-label="Grid view" aria-pressed={mode==='grid'} className={`rounded-full p-2 ${mode==='grid'?'bg-white shadow-sm dark:bg-white/15':''}`}><Grid2X2 size={17}/></button><button onClick={()=>setMode('list')} aria-label="List view" aria-pressed={mode==='list'} className={`rounded-full p-2 ${mode==='list'?'bg-white shadow-sm dark:bg-white/15':''}`}><List size={17}/></button></div></div><div className="mt-3 flex flex-wrap gap-2">{scopeOptions.map(s=><button key={s} onClick={()=>setScope(s)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${scope===s?'bg-[#141414] text-white dark:bg-white dark:text-[#141414]':'bg-[#F6F3EE] text-[#68635b] dark:bg-white/5 dark:text-[#d0c9be]'}`}>{s}</button>)}</div></Card>
    {loading?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><CardSkeleton/><CardSkeleton/><CardSkeleton/></div>:filtered.length===0?<EmptyState name="CalendarDays" tone="coral" title="No events found" description="Try another skill or loosen your filters to see what’s coming up." actionText="Clear filters" onAction={()=>{setQuery('');setScope('All events');setSkill('Any skill');setTeamSize('Any size');}}/>:<div className={mode==='grid'?'grid gap-4 md:grid-cols-2 xl:grid-cols-3':'space-y-4'}>{filtered.map((event,i)=><motion.article key={event.id} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:Math.min(i*.035,.18)}}><Card color={event.color||tones[i%tones.length]} className={`group relative overflow-hidden transition-transform duration-200 hover:-translate-y-1 ${mode==='list'?'flex flex-col gap-4 p-5 sm:flex-row sm:items-center':''}`}>
      <div className={`relative flex items-center justify-between overflow-hidden p-5 ${mode==='grid'?'h-36':'h-24 rounded-2xl sm:w-40 sm:shrink-0'}`}><div className="absolute inset-0 soft-grid opacity-30"/><GradientIcon name={event.category==='Datathon'?'Database':event.category==='Design sprint'?'Palette':'Code2'} tone={['sky','green','pink','amber','coral'][i%5]} tileSize={62} size={28} className="relative z-[1]"/><div className="relative z-[1] flex gap-2"><Badge>{event.scope}</Badge>{event.mode&&<Badge color="ink">{event.mode}</Badge>}</div>{mode==='grid'&&<span className="absolute -bottom-8 -right-2 display-font text-7xl font-extrabold opacity-[.07]">0{i+1}</span>}</div>
      <div className={`${mode==='grid'?'p-5 pt-0':'min-w-0 flex-1'}`}><div className="flex items-center gap-2 text-xs font-semibold text-[#777269] dark:text-[#c8c1b6]"><CalendarDays size={14}/>{new Intl.DateTimeFormat('en',{month:'long',day:'numeric'}).format(new Date(`${event.date}T12:00:00`))}<span>·</span>{event.category}</div><Link to={`/events/${event.id}`}><h2 className="display-font mt-2 text-xl font-extrabold tracking-tight transition hover:underline">{event.title}</h2></Link><p className="mt-2 line-clamp-2 text-xs leading-5 text-[#625e56] dark:text-[#d0c9be]">{event.description}</p><div className="mt-3 flex flex-wrap gap-2">{(event.skills||[]).slice(0,3).map(tag=><SkillChip key={tag} tone={['sky','green','pink'][i%3]}>{tag}</SkillChip>)}</div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-black/[.07] pt-4 dark:border-white/[.09]"><span className="flex items-center gap-2 text-[11px] font-semibold text-[#716c64] dark:text-[#c8c1b6]"><Users size={14}/>{event.teamSize} teammates <span>·</span> {event.registrations} joined</span><Button className="!px-4 !py-2.5 !text-xs" onClick={()=>{setRegisterMode('Looking for a team');setRegistering(event);}} disabled={registered[event.id]}>{registered[event.id]?'Registered':'Register'}{!registered[event.id]&&<ArrowRight className="arrow-slide" size={14}/>}</Button></div></div></Card></motion.article>)}</div>}
    <Modal open={!!registering} title="A spot with your name on it" onClose={()=>setRegistering(null)}><div className="rounded-2xl bg-[#DCE8D6] p-4 dark:bg-[#303a2d]"><p className="text-xs font-bold uppercase tracking-wider text-[#62715b] dark:text-[#cad7c0]">{registering?.category}</p><h3 className="display-font mt-1 font-extrabold">{registering?.title}</h3><p className="mt-1 text-xs text-[#68715f] dark:text-[#d0dac6]">{registering?.date} · {registering?.teamSize} teammates</p></div><fieldset className="mt-5 space-y-2"><legend className="mb-2 text-sm font-bold">How are you joining?</legend>{['Looking for a team','Already have a team','Going solo'].map(option=><label key={option} className="flex cursor-pointer items-center gap-3 rounded-2xl bg-white p-3 text-sm dark:bg-white/5"><input type="radio" name="registrationMode" checked={registerMode===option} onChange={()=>setRegisterMode(option)} className="accent-[#6f9b64]"/>{option}</label>)}</fieldset><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setRegistering(null)}>Maybe later</Button><Button onClick={handleRegister} showArrow>Confirm registration</Button></div></Modal>
  </div>;
}
