import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowDown, ArrowRight, ArrowUpRight, Moon, Sun, Sparkles, Users, CalendarDays, Code2, Palette, BrainCircuit, Smartphone, Database, Check } from 'lucide-react';
import { useTheme } from '../context/ThemeContext';
import { GradientIcon } from '../components/GradientIcon';
import { Badge, Button, Card } from '../components/ui';
import { events, students } from '../api/mockData';

const tones = ['sky','green','pink','amber','coral','teal'];
const how = [
  ['Build your profile','Show what you know, what you love, and what you want to learn.','UserRound','sky'],
  ['Find your event','Browse student events that fit your interests and ambition.','CalendarDays','coral'],
  ['Meet your people','See thoughtful teammate matches with skills that complement yours.','Users','green'],
  ['Make something real','Bring your team together and turn a good idea into a great project.','Rocket','amber']
];

export function Landing() {
  const { theme, toggleTheme } = useTheme();
  return <div className="min-h-screen overflow-hidden bg-[#F6F3EE] text-[#141414] dark:bg-[#151412] dark:text-[#f6f3ee]">
    <header className="relative z-10 mx-auto flex max-w-[1440px] items-center justify-between px-5 py-5 sm:px-10 lg:px-16">
      <Link to="/" className="flex items-center gap-2.5" aria-label="SkillSync home"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#141414] text-white dark:bg-white dark:text-[#141414]"><Sparkles size={19}/></span><span className="display-font text-xl font-extrabold tracking-tight">skill<span className="font-medium">sync</span></span></Link>
      <nav className="hidden items-center gap-8 text-sm font-medium text-[#615d56] dark:text-[#d0cbc2] md:flex"><a href="#how-it-works" className="hover:text-black dark:hover:text-white">How it works</a><a href="#events" className="hover:text-black dark:hover:text-white">Events</a><a href="#skills" className="hover:text-black dark:hover:text-white">Explore skills</a></nav>
      <div className="flex items-center gap-2 sm:gap-3"><button onClick={toggleTheme} className="grid h-10 w-10 place-items-center rounded-full hover:bg-black/5 dark:hover:bg-white/10" aria-label={`Switch to ${theme==='dark'?'light':'dark'} mode`}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button><Link to="/login" className="hidden px-3 py-2 text-sm font-semibold sm:inline">Log in</Link><Link to="/register"><Button className="!px-4 !py-2.5 sm:!px-5">Get started <ArrowRight className="arrow-slide" size={15}/></Button></Link></div>
    </header>

    <main>
      <section className="relative mx-auto grid max-w-[1440px] items-center gap-10 px-5 pb-16 pt-8 sm:px-10 sm:pt-14 lg:grid-cols-[1.05fr_.95fr] lg:gap-4 lg:px-16 lg:pb-24">
        <div className="relative z-[1]">
          <motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{duration:.45}} className="mb-6 inline-flex items-center gap-2 rounded-full bg-white/80 px-4 py-2 text-xs font-semibold text-[#625e56] shadow-sm dark:bg-white/10 dark:text-[#ded8ce]"><span className="h-2 w-2 rounded-full bg-[#7da873]"/> A better way to find your people</motion.div>
          <motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.55,delay:.08}} className="editorial-title display-font text-[clamp(4.1rem,9.4vw,8.5rem)] font-extrabold uppercase">Find your<br/><span className="editorial-italic ml-[.12em] inline-block pt-3 text-[.84em] normal-case">dream team</span></motion.h1>
          <motion.p initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{duration:.5,delay:.18}} className="mt-8 max-w-xl text-base leading-7 text-[#625e56] dark:text-[#c7c1b7] sm:text-lg sm:leading-8">Great projects start with the right people. Discover student events, show off your skills, and meet teammates who bring something different to the table.</motion.p>
          <motion.div initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:.5,delay:.26}} className="mt-8 flex flex-wrap items-center gap-3"><Link to="/register"><Button showArrow>Create your profile</Button></Link><Link to="/login" className="rounded-full px-5 py-3 text-sm font-semibold text-[#504d47] transition hover:bg-white/70 dark:text-[#ded8ce] dark:hover:bg-white/10">I already have an account</Link></motion.div>
          <div className="mt-10 flex items-center gap-4"><div className="flex -space-x-3">{students.slice(0,4).map(s=><img key={s.id} src={s.avatarUrl} alt="" className="h-10 w-10 rounded-full border-[3px] border-[#F6F3EE] object-cover dark:border-[#151412]"/>)}</div><p className="text-xs leading-5 text-[#6b665e] dark:text-[#c4beb4]"><strong className="text-[#141414] dark:text-white">30+ student profiles</strong><br/>ready to build something together</p></div>
        </div>

        <motion.div initial={{opacity:0,scale:.96,y:14}} animate={{opacity:1,scale:1,y:0}} transition={{duration:.65,delay:.12}} className="relative mx-auto w-full max-w-[610px] lg:ml-auto">
          <div className="absolute -right-2 top-0 h-40 w-40 rounded-full bg-[#f5c8a5] opacity-75 blur-3xl sm:right-4"/><div className="absolute -bottom-4 left-4 h-44 w-44 rounded-full bg-[#c7dcbf] opacity-70 blur-3xl"/>
          <div className="relative rounded-[34px] bg-[#DCE8D6] p-4 panel-shadow sm:rounded-[42px] sm:p-6">
            <div className="flex items-center justify-between px-1 pb-5"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#66715e]">Your next big idea</p><p className="display-font mt-1 text-xl font-bold tracking-tight">starts with a team</p></div><div className="grid h-10 w-10 place-items-center rounded-full bg-white/70"><ArrowUpRight size={18}/></div></div>
            <div className="rounded-[27px] bg-[#F6F3EE] p-4 sm:p-5 dark:bg-[#22211e]">
              <div className="flex items-start justify-between gap-3"><div><Badge color="green">A lovely match</Badge><h2 className="display-font mt-3 text-2xl font-extrabold tracking-tight">Meet Maya</h2><p className="mt-1 text-sm text-[#716d65] dark:text-[#c6c0b5]">Product designer · 3rd year</p></div><div className="relative grid h-[68px] w-[68px] place-items-center rounded-full" style={{background:'conic-gradient(#74a36b 0 92%, #e8e4db 92% 100%)'}}><div className="grid h-[56px] w-[56px] place-items-center rounded-full bg-[#F6F3EE] text-lg font-extrabold dark:bg-[#22211e]">92<span className="text-[10px]">%</span></div></div></div>
              <div className="mt-5 flex items-center gap-3 rounded-2xl bg-white p-3 dark:bg-white/10"><img src={students[1].avatarUrl} alt="Maya Shah" className="h-12 w-12 rounded-xl object-cover"/><div className="min-w-0 flex-1"><p className="text-sm font-bold">Maya Shah</p><p className="text-xs text-[#726d65] dark:text-[#ccc5ba]">Northstar Institute</p></div><div className="rounded-full bg-[#DCE8D6] px-3 py-1 text-xs font-bold dark:bg-[#394337]">92% fit</div></div>
              <div className="mt-4"><p className="text-xs font-bold uppercase tracking-wider text-[#777269] dark:text-[#c8c1b6]">Skills that click</p><div className="mt-2 flex flex-wrap gap-2"><span className="rounded-full bg-[#D8E8F4] px-3 py-1.5 text-xs font-semibold text-[#315e75]">React</span><span className="rounded-full bg-[#FBEEC3] px-3 py-1.5 text-xs font-semibold text-[#765f22]">Figma</span><span className="rounded-full bg-[#F8D9DF] px-3 py-1.5 text-xs font-semibold text-[#844b58]">Product thinking</span></div></div>
              <div className="mt-4 rounded-2xl bg-[#FBF3E9] p-3 text-xs leading-5 text-[#675f53] dark:bg-[#363128] dark:text-[#d8cebc]">“Your frontend skills pair beautifully with Maya’s product design and prototyping experience.”</div>
              <button className="mt-4 flex w-full items-center justify-center gap-2 rounded-full bg-[#141414] py-3 text-sm font-semibold text-white dark:bg-white dark:text-[#141414]">Say hello <ArrowRight size={16}/></button>
            </div>
            <div className="mt-4 flex items-center justify-between rounded-2xl bg-[#FBE1D0] px-4 py-3 dark:bg-[#40312b]"><div className="flex items-center gap-3"><GradientIcon name="CalendarDays" tone="coral" tileSize={40} size={19}/><div><p className="text-[11px] font-semibold uppercase tracking-wider text-[#806455] dark:text-[#dfbdab]">Coming up</p><p className="text-sm font-bold">Build for Tomorrow</p></div></div><span className="text-xs font-semibold">Oct 18 <ArrowRight className="ml-1 inline" size={13}/></span></div>
          </div>
          <div className="absolute -left-5 top-[43%] hidden -rotate-6 items-center gap-2 rounded-2xl bg-white px-4 py-3 shadow-lg dark:bg-[#272521] sm:flex"><span className="grid h-8 w-8 place-items-center rounded-xl bg-[#FBEEC3]"><Sparkles size={17}/></span><div><p className="text-xs font-bold">A good team feels different</p><p className="text-[10px] text-[#777269] dark:text-[#c9c2b8]">Find your missing piece</p></div></div>
        </motion.div>
      </section>

      <section className="mx-auto max-w-[1440px] px-5 pb-20 sm:px-10 lg:px-16"><Card color="peach" className="flex flex-col gap-7 p-7 sm:p-10 lg:flex-row lg:items-center lg:justify-between lg:p-12"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#8a6755] dark:text-[#e5bd9f]">More than a match</p><h2 className="display-font mt-3 text-3xl font-extrabold leading-tight tracking-[-.045em] sm:text-4xl">The best teams aren’t made of the same people.</h2><p className="mt-4 max-w-xl leading-7 text-[#665a50] dark:text-[#dfcbbd]">They’re made of people who bring different strengths, share the work, and make each other’s ideas better.</p></div><Link to="/register"><Button className="self-start lg:self-center" showArrow>Find your people</Button></Link><div className="flex items-center gap-3 lg:hidden">{tones.map((tone,i)=><GradientIcon key={tone} name={['Code2','BrainCircuit','Palette','Smartphone','Database','Users'][i]} tone={tone} tileSize={42} size={19}/>)}</div></Card></section>

      <section id="how-it-works" className="mx-auto max-w-[1440px] scroll-mt-10 px-5 pb-24 sm:px-10 lg:px-16"><div className="mb-10 flex items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#898278]">A few easy steps</p><h2 className="editorial-title display-font mt-4 text-5xl font-extrabold sm:text-7xl">Good things<br/><span className="editorial-italic normal-case">come together.</span></h2></div><ArrowDown className="mb-2 hidden sm:block" size={28}/></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{how.map(([title,desc,icon,tone],i)=><motion.div key={title} initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-40px'}} transition={{delay:i*.07}}><Card color={['sage','peach','sky','butter'][i]} className="h-full p-6"><div className="flex items-center justify-between"><GradientIcon name={icon} tone={tone}/><span className="display-font text-4xl font-extrabold opacity-25">0{i+1}</span></div><h3 className="display-font mt-8 text-xl font-extrabold tracking-tight">{title}</h3><p className="mt-3 text-sm leading-6 text-[#625e56] dark:text-[#d0c9be]">{desc}</p></Card></motion.div>)}</div></section>

      <section id="events" className="scroll-mt-10 bg-[#ebe7df] py-20 dark:bg-[#1d1c19]"><div className="mx-auto max-w-[1440px] px-5 sm:px-10 lg:px-16"><div className="mb-9 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#898278]">Make the next weekend count</p><h2 className="editorial-title display-font mt-3 text-5xl font-extrabold sm:text-6xl">On the horizon</h2></div><Link to="/register" className="hidden text-sm font-bold sm:inline-flex sm:items-center sm:gap-2">Browse events <ArrowRight size={16}/></Link></div><div className="grid gap-4 md:grid-cols-3">{events.slice(0,3).map((event,i)=><Card key={event.id} color={event.color} className="group p-6 transition-transform duration-200 hover:-translate-y-1"><div className="flex items-center justify-between"><Badge>{event.category}</Badge><ArrowUpRight size={17} className="opacity-50 transition group-hover:-translate-y-1 group-hover:translate-x-1"/></div><p className="mt-8 text-xs font-semibold text-[#726d65] dark:text-[#c9c2b8]">{event.date} · {event.mode}</p><h3 className="display-font mt-2 text-2xl font-extrabold tracking-tight">{event.title}</h3><p className="mt-3 min-h-[48px] text-sm leading-6 text-[#625e56] dark:text-[#d0c9be]">{event.description}</p><div className="mt-5 flex flex-wrap gap-2">{event.skills.slice(0,2).map(skill=><span key={skill} className="rounded-full bg-white/65 px-3 py-1 text-[11px] font-semibold dark:bg-black/15">{skill}</span>)}</div></Card>)}</div></div></section>

      <section id="skills" className="mx-auto max-w-[1440px] px-5 py-20 sm:px-10 lg:px-16"><div className="grid items-center gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#898278]">Every strength has a place</p><h2 className="editorial-title display-font mt-4 text-5xl font-extrabold sm:text-6xl">Bring what<br/><span className="editorial-italic normal-case">you do best.</span></h2><p className="mt-6 max-w-md leading-7 text-[#625e56] dark:text-[#c7c1b7]">Every role matters. Show teammates how you think, design, build, and solve.</p><Link to="/register" className="mt-7 inline-flex"><Button showArrow>Explore your strengths</Button></Link></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{[['Frontend','Code2','sky'],['Backend','Server','green'],['AI / ML','BrainCircuit','pink'],['Design','Palette','amber'],['Mobile','Smartphone','coral'],['Data','Database','teal']].map(([name,icon,tone])=><div key={name} className="flex items-center gap-3 rounded-2xl bg-white/70 p-3 dark:bg-white/[.06] sm:gap-4 sm:p-4"><GradientIcon name={icon} tone={tone} tileSize={44} size={20}/><span className="text-sm font-bold">{name}</span><Check className="ml-auto hidden text-[#6f9b64] sm:block" size={16}/></div>)}</div></div></section>
    </main>

    <footer className="mx-5 mb-5 rounded-[32px] bg-[#141414] px-6 py-10 text-white dark:bg-[#25231f] sm:mx-10 sm:p-12 lg:mx-16"><div className="mx-auto flex max-w-[1280px] flex-col gap-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#c3d4b9]">Your next chapter is a team sport</p><h2 className="editorial-title display-font mt-4 text-5xl font-extrabold sm:text-7xl">Make it<br/><span className="editorial-italic normal-case">together.</span></h2></div><div><Link to="/register"><Button className="!bg-white !text-[#141414]" showArrow>Get started</Button></Link><p className="mt-4 text-xs text-white/55">SkillSync · Make good things together.</p></div></div></footer>
  </div>;
}
