import React,{useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {AnimatePresence,motion} from 'framer-motion';
import {ArrowLeft,ArrowRight,Check,Plus,Sparkles} from 'lucide-react';
import {useAuth} from '../context/AuthContext';
import {useTheme} from '../context/ThemeContext';
import {useToast} from '../context/ToastContext';
import {triggerConfetti} from '../components/Confetti';
import {Button,Card,Input,ProgressRing,SkillChip} from '../components/ui';

const steps=['A few basics','Your strengths','Around the web','All set'];
const suggestions=[['React','Frontend'],['TypeScript','Frontend'],['Python','AI/ML'],['Figma','Design'],['SQL','Data'],['Java','Backend'],['Flutter','Mobile'],['Product design','Design']];
const tones={Frontend:'sky',Backend:'green','AI/ML':'pink',Design:'amber',Mobile:'coral',Data:'teal'};

export function Onboarding(){
  const {user,updateProfile}=useAuth();const {theme,toggleTheme}=useTheme();const toast=useToast();const navigate=useNavigate();const [step,setStep]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const [form,setForm]=useState({fullName:user?.fullName||'',collegeName:user?.collegeName||'',major:user?.major||'',graduationYear:user?.graduationYear||2027,bio:user?.bio||'',skills:user?.skills||[],githubUrl:user?.githubUrl||'',linkedinUrl:user?.linkedinUrl||'',portfolioUrl:user?.portfolioUrl||''});
  const patch=(key,value)=>setForm(prev=>({...prev,[key]:value}));
  const toggleSkill=(name,category)=>{const has=form.skills.find(s=>s.skillName===name);patch('skills',has?form.skills.filter(s=>s.skillName!==name):[...form.skills,{id:`skill-${Date.now()}-${name}`,skillName:name,category,proficiencyLevel:'Intermediate'}]);};
  const advance=async()=>{setError('');if(step===0&&(!form.fullName.trim()||!form.collegeName.trim())){setError('Add your name and college to keep going.');return;}if(step===1&&!form.skills.length){setError('Pick at least one skill to help us find a good fit.');return;}if(step<2){setStep(x=>x+1);return;}setBusy(true);const response=await updateProfile({...form,role:user?.role||'STUDENT',profileCompleteness:75,onboardingComplete:true});setBusy(false);if(!response.success){setError(response.error||'Could not save your profile. Try again.');return;}setStep(3);triggerConfetti();toast.success('Your profile is ready to go!');};
  const finish=()=>navigate('/dashboard');
  return <div className="min-h-screen bg-[#F6F3EE] px-4 py-6 text-[#141414] dark:bg-[#151412] dark:text-[#f6f3ee] sm:py-10"><div className="mx-auto max-w-3xl"><header className="flex items-center justify-between"><Link to="/" className="display-font text-lg font-extrabold">skill<span className="font-medium">sync</span></Link><div className="flex items-center gap-3"><span className="text-xs font-medium text-[#807a71]">Set up your space · about 2 minutes</span><button onClick={toggleTheme} aria-label={`Switch to ${theme==='dark'?'light':'dark'} mode`} className="grid h-9 w-9 place-items-center rounded-full hover:bg-black/5 dark:hover:bg-white/10">{theme==='dark'?'☀':'☾'}</button></div></header>
    <Card className="mt-8 overflow-hidden"><div className="grid gap-7 p-5 sm:grid-cols-[190px_1fr] sm:p-8"><aside className="sm:border-r sm:border-black/5 sm:pr-6 dark:sm:border-white/10"><p className="text-xs font-bold uppercase tracking-[.17em] text-[#898278]">Getting started</p><div className="mt-5 space-y-4">{steps.map((title,index)=><div key={title} className="flex items-center gap-3"><span className={`grid h-8 w-8 place-items-center rounded-full text-xs font-bold ${index<step?'bg-[#DCE8D6] text-[#38623a]':index===step?'bg-[#141414] text-white dark:bg-white dark:text-[#141414]':'bg-black/5 text-[#8c867c] dark:bg-white/10'}`}>{index<step?<Check size={15}/>:index+1}</span><span className={`text-xs ${index===step?'font-bold':'text-[#898278]'}`}>{title}</span></div>)}</div><div className="mt-6 hidden sm:block"><ProgressRing value={Math.round(step/3*100)} label={`Step ${step+1} of 4`}/></div></aside>
      <div className="min-h-[390px]">{step<3?<><div className="mb-6 h-1.5 overflow-hidden rounded-full bg-black/5 dark:bg-white/10"><motion.div className="h-full rounded-full bg-[#6f9b64]" animate={{width:`${((step+1)/3)*100}%`}}/></div><p className="text-xs font-bold uppercase tracking-[.17em] text-[#898278]">Step {step+1} of 3</p><h1 className="display-font mt-2 text-3xl font-extrabold tracking-tight">{['Start with the basics','What do you like to do?','A few places to find your work'][step]}</h1><p className="mt-2 text-sm text-[#6d685f] dark:text-[#c8c1b6]">{['Just enough to make your profile feel like you.','Pick a few strengths. You can change these any time.','Links help possible teammates see what you’ve made.'][step]}</p>
      <AnimatePresence mode="wait"><motion.div key={step} initial={{opacity:0,x:12}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-12}} transition={{duration:.16}} className="mt-6 space-y-4">
        {step===0&&<><Input label="Full name" value={form.fullName} onChange={e=>patch('fullName',e.target.value)} placeholder="Your name"/><Input label="College or university" value={form.collegeName} onChange={e=>patch('collegeName',e.target.value)} placeholder="Your college"/><div className="grid gap-4 sm:grid-cols-2"><Input label="Major" value={form.major} onChange={e=>patch('major',e.target.value)} placeholder="Computer Science"/><Input label="Graduation year" type="number" min="2024" max="2035" value={form.graduationYear} onChange={e=>patch('graduationYear',e.target.value)}/></div><label className="block text-sm font-semibold">A quick intro<textarea rows="3" maxLength={350} value={form.bio} onChange={e=>patch('bio',e.target.value)} placeholder="What do you love learning or building?" className="auth-input mt-2 resize-y font-normal"/></label></>}
        {step===1&&<><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{suggestions.map(([name,category])=>{const selected=form.skills.some(s=>s.skillName===name);return <button key={name} type="button" onClick={()=>toggleSkill(name,category)} className={`flex items-center justify-between rounded-2xl px-3 py-3 text-left text-xs font-semibold transition ${selected?'bg-[#DCE8D6] ring-1 ring-[#8ba77b] dark:bg-[#313a2f]':'bg-[#F6F3EE] hover:bg-[#ebe7df] dark:bg-white/5 dark:hover:bg-white/10'}`}><span>{name}</span><span className="text-[#71816a]">{selected?<Check size={14}/>:<Plus size={14}/>}</span></button>;})}</div><div className="flex flex-wrap gap-2">{form.skills.map(s=><SkillChip key={s.id} tone={tones[s.category]||'sky'}>{s.skillName}</SkillChip>)}</div>{form.skills.length>0&&<label className="block max-w-xs text-sm font-semibold">How confident do you feel?<select value={form.skills[0].proficiencyLevel} onChange={e=>patch('skills',form.skills.map((s,i)=>i===0?{...s,proficiencyLevel:e.target.value}:s))} className="auth-input mt-2">{['Beginner','Intermediate','Advanced'].map(l=><option key={l}>{l}</option>)}</select></label>}</>}
        {step===2&&<><Input label="GitHub profile" value={form.githubUrl} onChange={e=>patch('githubUrl',e.target.value)} placeholder="https://github.com/you"/><Input label="LinkedIn profile" value={form.linkedinUrl} onChange={e=>patch('linkedinUrl',e.target.value)} placeholder="https://linkedin.com/in/you"/><Input label="Portfolio or personal site" value={form.portfolioUrl} onChange={e=>patch('portfolioUrl',e.target.value)} placeholder="https://your.site"/><p className="rounded-2xl bg-[#D8E8F4] p-4 text-xs leading-5 text-[#315e75] dark:bg-[#29363d] dark:text-[#c2e1ec]">You can skip links for now and add them later from your profile.</p></>}
      </motion.div></AnimatePresence>{error&&<p role="alert" className="mt-4 text-sm font-medium text-[#a33c33]">{error}</p>}<div className="mt-8 flex items-center justify-between border-t border-black/5 pt-5 dark:border-white/10"><Button variant="quiet" onClick={()=>step===0?navigate('/dashboard'):setStep(x=>x-1)}>{step===0?'Do this later':'Back'}</Button><Button onClick={advance} disabled={busy} showArrow>{busy?'Saving…':step===2?'Finish profile':'Continue'}</Button></div></>:<div className="flex min-h-[410px] flex-col items-center justify-center text-center"><div className="grid h-20 w-20 place-items-center rounded-[28px] bg-[#DCE8D6]"><Sparkles size={34} className="text-[#618354]"/></div><h1 className="display-font mt-6 text-3xl font-extrabold">You’re in good shape.</h1><p className="mt-3 max-w-sm text-sm leading-6 text-[#6d685f] dark:text-[#c8c1b6]">Your profile is ready. Let’s find an event and meet the people who’ll help your idea grow.</p><Button className="mt-7" onClick={finish} showArrow>Explore my dashboard</Button></div>}</div>
    </div></Card><p className="mt-5 text-center text-xs text-[#8d877e]">You’re always in control of what’s on your profile.</p></div></div>;
}
