import React, { useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowUpRight, CodeXml, Globe, Link as LinkIcon, Plus, Save, Trash2, Upload, UserRound, Sparkles } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import { triggerConfetti } from '../components/Confetti';
import { Avatar, Badge, Button, Card, Input, ProgressRing, SkillChip } from '../components/ui';

const categories=['Frontend','Backend','AI/ML','Design','Mobile','Data'];
const levels=['Beginner','Intermediate','Advanced'];
const categoryTone={Frontend:'sky',Backend:'green','AI/ML':'pink',Design:'amber',Mobile:'coral',Data:'teal'};

export function Profile(){
  const {user,updateProfile}=useAuth();const toast=useToast();const [editing,setEditing]=useState(false);const [saving,setSaving]=useState(false);const [newSkill,setNewSkill]=useState('');const [newCategory,setNewCategory]=useState('Frontend');const [newLevel,setNewLevel]=useState('Intermediate');const [errors,setErrors]=useState({});
  const [form,setForm]=useState(()=>({...user,skills:user?.skills||[],fullName:user?.fullName||'',collegeName:user?.collegeName||'',major:user?.major||'',graduationYear:user?.graduationYear||2027,bio:user?.bio||'',githubUrl:user?.githubUrl||'',linkedinUrl:user?.linkedinUrl||'',portfolioUrl:user?.portfolioUrl||'',lookingForTeam:user?.lookingForTeam??true}));
  const completeness=useMemo(()=>{const values=[form.fullName,form.collegeName,form.major,form.bio,form.githubUrl||form.portfolioUrl,form.linkedinUrl,form.skills?.length>=3];return Math.round(values.filter(Boolean).length/values.length*100);},[form]);
  const set=(key,value)=>setForm(f=>({...f,[key]:value}));
  const validate=()=>{const next={};if(!form.fullName.trim())next.fullName='Please add your name.';for(const key of ['githubUrl','linkedinUrl','portfolioUrl'])if(form[key]&&!/^https?:\/\//i.test(form[key]))next[key]='Enter a complete URL starting with https://';setErrors(next);return Object.keys(next).length===0;};
  const addSkill=()=>{const name=newSkill.trim();if(!name)return;if(form.skills.some(s=>s.skillName.toLowerCase()===name.toLowerCase())){toast.info('That skill is already on your profile.');return;}set('skills',[...form.skills,{id:`skill-${Date.now()}`,skillName:name,category:newCategory,proficiencyLevel:newLevel}]);setNewSkill('');};
  const save=async(e)=>{e?.preventDefault();if(!validate())return;setSaving(true);const response=await updateProfile({...form,profileCompleteness:completeness});setSaving(false);if(response.success){setEditing(false);toast.success('Your profile is up to date.');if(completeness>=90)triggerConfetti();}else toast.error(response.error||'Profile could not be saved.');};
  const resumeUpload=(e)=>{const file=e.target.files?.[0];if(!file)return;if(file.size>8*1024*1024){toast.error('Choose a resume under 8 MB.');return;}set('resumeName',file.name);toast.success('Resume selected for your profile.');};
  return <div className="mx-auto max-w-5xl space-y-6 pb-24 md:pb-10">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#898278]">Your story, in progress</p><h1 className="editorial-title display-font mt-2 text-5xl font-extrabold sm:text-6xl">A little more<br/><span className="editorial-italic normal-case">about you.</span></h1></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>setEditing(x=>!x)}>{editing?'Preview profile':'Edit profile'}</Button>{editing&&<Button onClick={save} disabled={saving}><Save size={16}/>{saving?'Saving…':'Save changes'}</Button>}</div></div>
    <Card color="sky" className="relative overflow-hidden"><div className="h-36 bg-[linear-gradient(110deg,#d8e8f4_0%,#fbeec3_54%,#fbe1d0_100%)] dark:bg-[linear-gradient(110deg,#29363d_0%,#403b2a_54%,#40312b_100%)]"/><div className="relative flex flex-col gap-5 px-6 pb-6 sm:flex-row sm:items-end sm:justify-between"><div className="-mt-12 flex items-end gap-4"><Avatar src={user?.avatarUrl} name={form.fullName} size={96} className="border-4 border-[#D8E8F4] dark:border-[#29363d]"/><div className="pb-1"><h2 className="display-font text-2xl font-extrabold">{form.fullName||'Your name'}</h2><p className="mt-1 text-sm text-[#625e56] dark:text-[#d0c9be]">{form.major||'Student maker'} · {form.collegeName||'Your college'}</p></div></div><div className="flex items-center gap-3 sm:pb-1"><Badge color={form.lookingForTeam?'green':'ink'}>{form.lookingForTeam?'Open to teammates':'Not looking right now'}</Badge><ProgressRing size={52} stroke={4} value={completeness}/></div></div></Card>

    {editing?<form onSubmit={save} noValidate className="space-y-5">
      <Card className="p-6"><div className="mb-5 flex items-center gap-3"><UserRound size={20}/><div><h2 className="display-font text-lg font-extrabold">The basics</h2><p className="text-xs text-[#817b71]">Help teammates get to know you.</p></div></div><div className="grid gap-4 sm:grid-cols-2"><Input label="Full name" value={form.fullName} onChange={e=>set('fullName',e.target.value)} error={errors.fullName}/><Input label="College or university" value={form.collegeName} onChange={e=>set('collegeName',e.target.value)}/><Input label="Major" value={form.major} onChange={e=>set('major',e.target.value)}/><Input label="Graduation year" type="number" min="2024" max="2035" value={form.graduationYear} onChange={e=>set('graduationYear',e.target.value)}/><label className="text-sm font-semibold sm:col-span-2">A few words about you<textarea rows="4" maxLength={500} value={form.bio} onChange={e=>set('bio',e.target.value)} placeholder="What do you like to build? What are you learning?" className="auth-input mt-2 resize-y font-normal"/><span className="mt-1 block text-right text-xs text-[#898278]">{form.bio.length}/500</span></label><label className="flex items-center gap-3 rounded-2xl bg-[#F6F3EE] p-4 text-sm font-semibold dark:bg-white/5 sm:col-span-2"><input type="checkbox" checked={form.lookingForTeam} onChange={e=>set('lookingForTeam',e.target.checked)} className="h-4 w-4 accent-[#6f9b64]"/>I’m open to meeting teammates</label></div></Card>
      <Card className="p-6"><h2 className="display-font text-lg font-extrabold">Skills and confidence</h2><p className="mb-5 mt-1 text-xs text-[#817b71]">Add a skill and choose the level you feel comfortable sharing.</p><div className="flex flex-wrap gap-2">{form.skills.map(skill=><span key={skill.id||skill.skillName} className="inline-flex items-center gap-2 rounded-full bg-[#F6F3EE] py-1 pl-3 dark:bg-white/10"><SkillChip tone={categoryTone[skill.category]||'sky'}>{skill.skillName} · {skill.proficiencyLevel}</SkillChip><button type="button" onClick={()=>set('skills',form.skills.filter(s=>s!==skill))} className="mr-2 rounded-full p-1 hover:bg-black/10 dark:hover:bg-white/10" aria-label={`Remove ${skill.skillName}`}><Trash2 size={13}/></button></span>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_150px_160px_auto]"><Input aria-label="Skill name" list="skill-suggestions" placeholder="e.g. React" value={newSkill} onChange={e=>setNewSkill(e.target.value)}/><datalist id="skill-suggestions">{['React','TypeScript','Python','Java','Figma','SQL','Machine Learning','Node.js','Flutter','Spring Boot'].map(x=><option key={x} value={x}/>)}</datalist><select aria-label="Skill category" value={newCategory} onChange={e=>setNewCategory(e.target.value)} className="auth-input">{categories.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Proficiency" value={newLevel} onChange={e=>setNewLevel(e.target.value)} className="auth-input">{levels.map(l=><option key={l}>{l}</option>)}</select><Button type="button" onClick={addSkill}><Plus size={16}/>Add skill</Button></div></Card>
      <Card className="p-6"><h2 className="display-font text-lg font-extrabold">Find me around the web</h2><p className="mb-5 mt-1 text-xs text-[#817b71]">Links give teams a window into your work.</p><div className="grid gap-4 sm:grid-cols-2"><Input label="GitHub" type="url" placeholder="https://github.com/you" value={form.githubUrl} onChange={e=>set('githubUrl',e.target.value)} error={errors.githubUrl}/><Input label="LinkedIn" type="url" placeholder="https://linkedin.com/in/you" value={form.linkedinUrl} onChange={e=>set('linkedinUrl',e.target.value)} error={errors.linkedinUrl}/><Input label="Portfolio" type="url" placeholder="https://your.site" value={form.portfolioUrl} onChange={e=>set('portfolioUrl',e.target.value)} error={errors.portfolioUrl}/><label className="block text-sm font-semibold">Resume (PDF, up to 8 MB)<span className="mt-2 flex items-center gap-3 rounded-2xl border border-dashed border-black/15 p-3 text-xs font-medium text-[#6e695f] dark:border-white/20 dark:text-[#d0c9be]"><Upload size={17}/><input type="file" accept="application/pdf,.pdf" onChange={resumeUpload} className="min-w-0 flex-1 text-xs"/>{form.resumeName&&<span className="max-w-24 truncate">{form.resumeName}</span>}</span></label></div></Card><div className="flex justify-end"><Button type="submit" disabled={saving} showArrow>{saving?'Saving…':'Save profile'}</Button></div>
    </form>:<div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="space-y-5"><Card className="p-6"><h2 className="display-font text-lg font-extrabold">A little about {form.fullName?.split(' ')[0]||'me'}</h2><p className="mt-3 text-sm leading-7 text-[#625e56] dark:text-[#d0c9be]">{form.bio||'Add a quick introduction so future teammates can learn what you enjoy building.'}</p></Card><Card className="p-6"><div className="flex items-center justify-between"><h2 className="display-font text-lg font-extrabold">What I bring</h2><Badge>{form.skills.length} skills</Badge></div><div className="mt-4 flex flex-wrap gap-2">{form.skills.map(skill=><SkillChip key={skill.id||skill.skillName} tone={categoryTone[skill.category]||'sky'}>{skill.skillName} · {skill.proficiencyLevel}</SkillChip>)}</div></Card><Card color="butter" className="p-6"><h2 className="display-font text-lg font-extrabold">A project I’m proud of</h2><p className="mt-2 text-sm leading-6 text-[#625e56] dark:text-[#d0c9be]">Share a link to something you made, learned from, or would love to make better.</p><div className="mt-4 flex flex-wrap gap-3">{[[CodeXml,form.githubUrl,'GitHub'],[Globe,form.linkedinUrl,'LinkedIn'],[LinkIcon,form.portfolioUrl,'Portfolio']].filter(([,url])=>url).map(([Icon,url,label])=><a key={label} href={url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-white/70 px-4 py-2 text-xs font-bold dark:bg-black/10"><Icon size={14}/>{label}<ArrowUpRight size={12}/></a>)}</div></Card></div><div className="space-y-5"><Card color="sage" className="p-6"><div className="flex items-center gap-3"><Sparkles size={19}/><h2 className="display-font font-extrabold">Make your profile shine</h2></div><p className="mt-3 text-sm leading-6 text-[#5f6759] dark:text-[#d1dbcb]">A clear bio, a couple projects, and skill levels help good teammates see the shape of your strengths.</p><Button variant="secondary" className="mt-5" onClick={()=>setEditing(true)}>Add a little more</Button></Card><Card className="p-6"><h2 className="display-font font-extrabold">Student at</h2><p className="mt-2 text-sm">{form.collegeName||'Your college'}</p><p className="mt-1 text-xs text-[#777269]">{form.major||'Field of study'} · Class of {form.graduationYear||'—'}</p>{form.resumeName&&<p className="mt-4 rounded-xl bg-[#F6F3EE] p-3 text-xs font-semibold dark:bg-white/5">Resume on file: {form.resumeName}</p>}</Card></div></div>}
  </div>;
}
