import React,{useEffect,useMemo,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {ArrowRight,MapPin,Search,Users} from 'lucide-react';
import {motion} from 'framer-motion';
import {studentsApi} from '../api/client';
import {useAuth} from '../context/AuthContext';
import {useToast} from '../context/ToastContext';
import {Avatar,Badge,Button,Card,SkillChip} from '../components/ui';
import {ProgressRing} from '../components/ui';
import {GradientIcon} from '../components/GradientIcon';
import {EmptyState} from '../components/EmptyState';
import {ProfileSkeleton} from '../components/Skeleton';

const tones=['sage','peach','sky','butter','blush'];
const toneFor={Frontend:'sky',Backend:'green','AI/ML':'pink',Design:'amber',Mobile:'coral',Data:'teal'};
export function Students(){
  const {user}=useAuth();const toast=useToast();const[people,setPeople]=useState([]);const[loading,setLoading]=useState(true);const[query,setQuery]=useState('');const[skill,setSkill]=useState('All skills');const[available,setAvailable]=useState(false);
  useEffect(()=>{studentsApi.list().then(({data})=>setPeople(data.filter(s=>s.id!==user?.id))).catch(()=>toast.error('Student directory could not be loaded.')).finally(()=>setLoading(false));},[user?.id]);
  const skillOptions=useMemo(()=>['All skills',[...new Set(people.flatMap(p=>(p.skills||[]).map(s=>s.skillName)))].sort()],[people]);
  const filtered=people.filter(p=>{const q=query.toLowerCase();return(!q||`${p.fullName} ${p.major} ${p.collegeName} ${(p.skills||[]).map(s=>s.skillName).join(' ')}`.toLowerCase().includes(q))&&(skill==='All skills'||p.skills?.some(s=>s.skillName===skill))&&(!available||p.lookingForTeam);});
  return <div className="mx-auto max-w-6xl space-y-7 pb-24 md:pb-10"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-[#898278]">Build something better together</p><h1 className="editorial-title display-font mt-2 text-5xl font-extrabold sm:text-6xl">Meet your<br/><span className="editorial-italic normal-case">next teammate.</span></h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[#6b665e] dark:text-[#c8c1b6]">Look for people who share your curiosity and bring a few strengths of their own.</p></header>
    <Card className="grid gap-3 p-4 sm:grid-cols-[1fr_220px_auto] sm:items-center"><label className="relative"><Search size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#898278]"/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search students" placeholder="Search a name, major, college, or skill" className="auth-input pl-10"/></label><select aria-label="Filter by skill" value={skill} onChange={e=>setSkill(e.target.value)} className="auth-input">{skillOptions.map(s=><option key={s}>{s}</option>)}</select><label className="flex cursor-pointer items-center gap-2 rounded-full bg-[#F6F3EE] px-4 py-3 text-xs font-semibold dark:bg-white/5"><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)} className="accent-[#6f9b64]"/>Looking for a team</label></Card>
    <div className="flex items-center justify-between"><p className="text-xs font-semibold text-[#898278]">{filtered.length} students</p><Badge color="green"><Users size={13} className="mr-1.5"/>{people.filter(p=>p.lookingForTeam).length} open to teammates</Badge></div>
    {loading?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><ProfileSkeleton/><ProfileSkeleton/><ProfileSkeleton/></div>:filtered.length===0?<EmptyState name="Users" tone="green" title="No students found" description="Try another name, skill, or filter to find people in the community." actionText="Clear search" onAction={()=>{setQuery('');setSkill('All skills');setAvailable(false);}}/>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((person,i)=><motion.div key={person.id} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:Math.min(i*.025,.18)}}><Card color={tones[i%tones.length]} className="h-full p-5 transition-transform hover:-translate-y-1"><div className="flex items-start gap-3"><Avatar src={person.avatarUrl} name={person.fullName} size={56}/><div className="min-w-0 flex-1"><h2 className="truncate font-bold">{person.fullName}</h2><p className="truncate text-xs text-[#5f7180] dark:text-[#d2dce2]">{person.major}</p><p className="mt-1 flex items-center gap-1 truncate text-[10px] text-[#777269]"><MapPin size={11}/>{person.collegeName}</p></div><ProgressRing value={person.profileCompleteness||70} size={45} stroke={4} label={`${person.profileCompleteness||70}% profile complete`}/></div><p className="mt-4 line-clamp-2 min-h-10 text-xs leading-5 text-[#625e56] dark:text-[#d0c9be]">{person.bio||'A student maker looking forward to learning and building with a team.'}</p><div className="mt-4 flex flex-wrap gap-2">{(person.skills||[]).slice(0,3).map(s=><SkillChip key={s.id||s.skillName} tone={toneFor[s.category]||'sky'}>{s.skillName}</SkillChip>)}</div><div className="mt-5 flex items-center justify-between border-t border-black/[.07] pt-4 dark:border-white/[.09]"><Badge color={person.lookingForTeam?'green':'ink'}>{person.lookingForTeam?'Looking for teammates':'Open to projects'}</Badge><Link to={`/students/${person.id}`} className="inline-flex items-center gap-1 text-xs font-bold">Get to know them <ArrowRight size={13}/></Link></div></Card></motion.div>)}</div>}
  </div>;
}

export function StudentDetail(){
  const{ id }=useParams();const toast=useToast();const[person,setPerson]=useState(null);
  useEffect(()=>{studentsApi.byId(id).then(({data})=>setPerson(data)).catch(()=>toast.error('Student profile could not be loaded.'));},[id]);
  if(!person)return <div className="mx-auto h-64 max-w-4xl animate-pulse rounded-3xl bg-black/5 dark:bg-white/10"/>;
  return <div className="mx-auto max-w-4xl space-y-6 pb-24 md:pb-10"><Link to="/students" className="text-sm font-semibold text-[#777269]">← Student directory</Link><Card color="sky" className="overflow-hidden"><div className="h-36 bg-[linear-gradient(110deg,#d8e8f4,#dce8d6,#fbeec3)] dark:bg-[linear-gradient(110deg,#29363d,#303a2d,#403b2a)]"/><div className="flex flex-col gap-5 p-6 sm:flex-row sm:items-end sm:justify-between"><div className="-mt-14 flex items-end gap-4"><Avatar src={person.avatarUrl} name={person.fullName} size={92} className="border-4 border-[#D8E8F4] dark:border-[#29363d]"/><div className="pb-1"><Badge color={person.lookingForTeam?'green':'ink'}>{person.lookingForTeam?'Looking for a team':'Open to projects'}</Badge><h1 className="display-font mt-2 text-2xl font-extrabold">{person.fullName}</h1><p className="text-xs text-[#6b665e] dark:text-[#c8c1b6]">{person.major} · {person.collegeName}</p></div></div><Link to={`/teams/create?candidate=${person.id}`}><Button showArrow>Build a team together</Button></Link></div></Card><div className="grid gap-5 lg:grid-cols-[1fr_300px]"><Card className="p-6"><h2 className="display-font text-lg font-extrabold">About {person.fullName.split(' ')[0]}</h2><p className="mt-3 text-sm leading-7 text-[#625e56] dark:text-[#d0c9be]">{person.bio||'This student is excited to learn, make, and work with thoughtful teams.'}</p><h3 className="mt-7 font-bold">Strengths and skills</h3><div className="mt-3 flex flex-wrap gap-2">{person.skills.map(s=><SkillChip key={s.id||s.skillName} tone={toneFor[s.category]||'sky'}>{s.skillName} · {s.proficiencyLevel}</SkillChip>)}</div></Card><Card color="butter" className="p-6"><h2 className="display-font text-lg font-extrabold">Find their work</h2><div className="mt-4 space-y-3">{[[person.githubUrl,'GitHub'],[person.linkedinUrl,'LinkedIn'],[person.portfolioUrl,'Portfolio']].filter(([url])=>url).map(([url,label])=><a key={label} target="_blank" rel="noreferrer" href={url} className="flex items-center justify-between rounded-xl bg-white/70 px-4 py-3 text-xs font-bold dark:bg-black/10">{label}<ArrowRight size={14}/></a>)}</div><p className="mt-5 text-xs leading-5 text-[#726b5d] dark:text-[#ddd2b9]">{person.fullName.split(' ')[0]} is in the class of {person.graduationYear||'—'}.</p></Card></div></div>;
}
