import React,{useEffect,useMemo,useState} from 'react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {ArrowLeft,ArrowRight,Check,Plus,Users,Sparkles,Send} from 'lucide-react';
import {motion} from 'framer-motion';
import {Radar,RadarChart,PolarGrid,PolarAngleAxis,PolarRadiusAxis,ResponsiveContainer,Tooltip} from 'recharts';
import {eventsApi,studentsApi,teamsApi,invitesApi} from '../api/client';
import {useAuth} from '../context/AuthContext';
import {useToast} from '../context/ToastContext';
import {triggerConfetti} from '../components/Confetti';
import {Avatar,Badge,Button,Card,ProgressRing,SkillChip} from '../components/ui';
import {GradientIcon} from '../components/GradientIcon';

const stepTitles=['Choose an event','Shape your team','Bring a few people','Find the missing piece'];
const colors=['sage','peach','sky','butter'];

export function TeamFormation(){
  const{user}=useAuth();const toast=useToast();const navigate=useNavigate();const[params]=useSearchParams();const existingTeamId=params.get('team');const candidateId=params.get('candidate');
  const[step,setStep]=useState(existingTeamId?3:0);const[events,setEvents]=useState([]);const[students,setStudents]=useState([]);const[eventId,setEventId]=useState('');const[name,setName]=useState('');const[size,setSize]=useState(4);const[selected,setSelected]=useState([]);const[team,setTeam]=useState(null);const[recs,setRecs]=useState([]);const[gap,setGap]=useState(null);const[invites,setInvites]=useState({});const[loading,setLoading]=useState(false);const[search,setSearch]=useState('');
  useEffect(()=>{Promise.all([eventsApi.list(),studentsApi.list()]).then(([e,s])=>{const available=s.data.filter(x=>x.id!==user?.id);setEvents(e.data);setStudents(available);if(candidateId){const candidate=available.find(x=>x.id===candidateId);if(candidate)setSelected([candidate]);}}).catch(()=>toast.error('Team setup data could not be loaded.'));},[user?.id,candidateId]);
  useEffect(()=>{if(!existingTeamId)return;teamsApi.byId(existingTeamId).then(({data})=>{setTeam(data);setEventId(data.eventId);setName(data.name);return Promise.all([teamsApi.recommendations(existingTeamId),teamsApi.skillGap(existingTeamId)]);}).then(([r,g])=>{setRecs(r.data);setGap(g.data);}).catch(()=>toast.error('Could not load team recommendations.'));},[existingTeamId]);
  const selectedEvent=events.find(e=>e.id===eventId);const capacity=Number(size)||4;const slots=Array.from({length:capacity},(_,i)=>i===0?{name:user?.fullName||'You',role:'Team lead'}:selected[i-1]?{name:selected[i-1].fullName,role:selected[i-1].major}:{name:'Open spot',role:'Ready for a teammate'});
  const list=useMemo(()=>students.filter(s=>`${s.fullName} ${s.major} ${s.skills.map(x=>x.skillName).join(' ')}`.toLowerCase().includes(search.toLowerCase())).slice(0,10),[students,search]);
  const toggle=(person)=>setSelected(current=>current.some(s=>s.id===person.id)?current.filter(s=>s.id!==person.id):current.length<capacity-1?[...current,person]:current);
  const next=async()=>{
    if(step===0&&!eventId){toast.info('Choose an event first.');return;}if(step===1&&!name.trim()){toast.info('Give your team a name to continue.');return;}
    if(step<2){setStep(s=>s+1);return;}
    if(step===2){setLoading(true);try{const {data}=await teamsApi.create({name:name.trim(),eventId,size:capacity,memberIds:selected.map(s=>s.id)});setTeam(data);const [recommendations,skillGap]=await Promise.all([teamsApi.recommendations(data.id),teamsApi.skillGap(data.id)]);setRecs(recommendations.data);setGap(skillGap.data);setStep(3);triggerConfetti();toast.success(`${name.trim()} is ready to meet its teammates.`);}catch{toast.error('Team could not be created. Try again.');}finally{setLoading(false);}return;}
    navigate(team?`/teams/${team.id}`:'/teams');
  };
  const sendInvite=async(person)=>{if(!team)return;setInvites(v=>({...v,[person.id]:'pending'}));toast.success(`Invite sent to ${person.fullName}.`);try{await invitesApi.create({teamId:team.id,teamName:team.name,eventName:selectedEvent?.title,candidateId:person.id,student:person,direction:'sent'});}catch{setInvites(v=>({...v,[person.id]:undefined}));toast.error('Invite could not be sent.');}};
  return <div className="mx-auto max-w-6xl space-y-6 pb-24 md:pb-10"><Link to="/teams" className="inline-flex items-center gap-2 text-sm font-semibold text-[#777269]"><ArrowLeft size={15}/> My teams</Link><header><p className="text-xs font-bold uppercase tracking-[.18em] text-[#898278]">Good teams start with a good mix</p><h1 className="editorial-title display-font mt-2 text-5xl font-extrabold sm:text-6xl">Find your<br/><span className="editorial-italic normal-case">right people.</span></h1></header>
    <div className="grid gap-6 lg:grid-cols-[220px_1fr]"><Card className="h-fit p-4"><p className="px-2 text-[10px] font-bold uppercase tracking-[.2em] text-[#898278]">Team builder</p><ol className="mt-4 space-y-2">{stepTitles.map((title,i)=><li key={title} className={`flex items-center gap-3 rounded-2xl px-3 py-3 text-xs ${step===i?'bg-[#DCE8D6] font-bold dark:bg-[#303a2d]':'text-[#7b756b]'}`}><span className={`grid h-7 w-7 place-items-center rounded-full ${i<step?'bg-[#6f9b64] text-white':'bg-black/5 dark:bg-white/10'}`}>{i<step?<Check size={14}/>:i+1}</span>{title}</li>)}</ol><div className="mt-5 border-t border-black/5 pt-4 dark:border-white/10"><p className="text-xs font-bold">Team slots</p><div className="mt-3 space-y-2">{slots.slice(0,capacity).map((slot,i)=><div key={`${i}-${slot.name}`} className="flex items-center gap-2"><span className={`grid h-6 w-6 place-items-center rounded-full text-[10px] ${i===0?'bg-[#FBEEC3]':'bg-black/5 dark:bg-white/10'}`}>{i===0?'★':i+1}</span><span className="min-w-0"><span className="block truncate text-[10px] font-semibold">{slot.name}</span><span className="block truncate text-[9px] text-[#898278]">{slot.role}</span></span></div>)}</div><p className="mt-3 text-[10px] text-[#898278]">{selected.length+1} of {capacity} spots filled</p></div></Card>
      <div className="min-w-0"><Card color={colors[step]} className="min-h-[540px] p-5 sm:p-7"><div className="flex items-center justify-between"><Badge>Step {step+1} of 4</Badge><ProgressRing value={Math.round((step+1)/4*100)} size={48} stroke={4}/></div>
      {step===0&&<div className="mt-6"><h2 className="display-font text-2xl font-extrabold">What are you building toward?</h2><p className="mt-2 text-sm text-[#6c675f] dark:text-[#d0c9be]">Pick the event so recommendations line up with the challenge.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{events.map(ev=><button key={ev.id} onClick={()=>setEventId(ev.id)} className={`rounded-2xl bg-white/75 p-4 text-left transition dark:bg-black/10 ${eventId===ev.id?'ring-2 ring-[#6f9b64]':''}`}><div className="flex items-center justify-between"><Badge>{ev.category}</Badge>{eventId===ev.id&&<Check size={16} className="text-[#618854]"/>}</div><h3 className="display-font mt-3 font-extrabold">{ev.title}</h3><p className="mt-1 text-xs text-[#777269]">{ev.date} · teams of {ev.teamSize}</p></button>)}</div></div>}
      {step===1&&<div className="mt-6 max-w-lg"><h2 className="display-font text-2xl font-extrabold">Give your crew a name.</h2><p className="mt-2 text-sm text-[#6c675f] dark:text-[#d0c9be]">You can change it as your idea takes shape.</p><label className="mt-6 block text-sm font-semibold">Team name<input value={name} onChange={e=>setName(e.target.value)} maxLength={50} placeholder="Something good is brewing" className="auth-input mt-2"/></label><label className="mt-5 block text-sm font-semibold">Team size<select value={size} onChange={e=>setSize(Number(e.target.value))} className="auth-input mt-2">{[2,3,4,5].map(n=><option key={n} value={n}>{n} students</option>)}</select></label>{selectedEvent&&<p className="mt-5 rounded-2xl bg-white/70 p-4 text-xs leading-5 dark:bg-black/10">{selectedEvent.title} welcomes teams of {selectedEvent.teamSize}. Pick a size that feels right for your crew.</p>}</div>}
      {step===2&&<div className="mt-6"><h2 className="display-font text-2xl font-extrabold">Start with people you know.</h2><p className="mt-2 text-sm text-[#6c675f] dark:text-[#d0c9be]">Optional: invite classmates you already have in mind. We’ll find complementary skills next.</p><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a student by name or skill" aria-label="Search students" className="auth-input mt-5"/><div className="mt-4 grid gap-2 sm:grid-cols-2">{list.slice(0,6).map(person=>{const chosen=selected.some(x=>x.id===person.id);const full=selected.length>=capacity-1;return <button key={person.id} onClick={()=>toggle(person)} disabled={!chosen&&full} className={`flex items-center gap-3 rounded-2xl bg-white/75 p-3 text-left dark:bg-black/10 ${chosen?'ring-2 ring-[#6f9b64]':''} disabled:opacity-50`}><Avatar src={person.avatarUrl} name={person.fullName} size={42}/><span className="min-w-0 flex-1"><span className="block truncate text-xs font-bold">{person.fullName}</span><span className="block truncate text-[10px] text-[#777269]">{person.skills.slice(0,2).map(s=>s.skillName).join(' · ')}</span></span><span className="grid h-7 w-7 place-items-center rounded-full bg-[#F6F3EE] dark:bg-white/10">{chosen?<Check size={14}/>:<Plus size={14}/>}</span></button>;})}</div><p className="mt-4 text-xs text-[#777269]">Your core crew: {selected.length+1} of {capacity}. You can invite more people after your team is created.</p></div>}
      {step===3&&<div className="mt-6"><h2 className="display-font text-2xl font-extrabold">Meet your missing piece.</h2><p className="mt-2 text-sm text-[#6c675f] dark:text-[#d0c9be]">A few students whose skills fit the team’s shape for <strong>{team?.name}</strong>.</p><div className="mt-5 grid gap-3">{recs.slice(0,6).map((person,i)=><div key={person.id} className="rounded-2xl bg-white/80 p-4 dark:bg-black/10"><div className="flex items-center gap-3"><Avatar src={person.avatarUrl} name={person.fullName} size={48}/><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-bold">{person.fullName}</h3><p className="truncate text-xs text-[#777269]">{person.major} · {person.collegeName}</p></div><ProgressRing value={person.matchScore} size={49} stroke={4} label={`${person.matchScore}% match`}/></div><div className="mt-3 flex flex-wrap gap-2">{person.matchingSkills.map(s=><SkillChip key={s} tone="green">{s}</SkillChip>)}</div><p className="mt-3 text-xs leading-5 text-[#625e56] dark:text-[#d0c9be]">{person.aiReason}</p><Button onClick={()=>sendInvite(person)} disabled={!!invites[person.id]} className="mt-3 !px-4 !py-2 !text-xs">{invites[person.id]?<><Check size={13}/>Invite pending</>:<><Send size={13}/>Invite {person.fullName.split(' ')[0]}</>}</Button></div>)}</div>
        {gap&&<div className="mt-7 rounded-2xl bg-white/80 p-4 dark:bg-black/10"><div className="flex items-center gap-3"><GradientIcon name="BrainCircuit" tone="amber" tileSize={38} size={17}/><div><h3 className="text-sm font-bold">Your team’s skill shape</h3><p className="text-[10px] text-[#777269]">The dotted line shows a balanced team mix.</p></div></div><div className="mt-3 h-64"><ResponsiveContainer width="100%" height="100%"><RadarChart data={gap.labels.map((label,i)=>({skill:label,team:gap.current[i],balanced:gap.required[i]}))}><PolarGrid stroke="currentColor" opacity={.15}/><PolarAngleAxis dataKey="skill" tick={{fontSize:10,fill:'#6e695f'}}/><PolarRadiusAxis domain={[0,5]} tick={false} axisLine={false}/><Radar name="Your team" dataKey="team" stroke="#d7866c" fill="#d7866c" fillOpacity={.32}/><Radar name="Balanced mix" dataKey="balanced" stroke="#6f9b64" fill="#6f9b64" fillOpacity={.12}/><Tooltip/></RadarChart></ResponsiveContainer></div><div className="flex justify-center gap-5 text-[10px]"><span className="text-[#bd7158]">● Current team</span><span className="text-[#63875a]">● Balanced team</span></div></div>}
      </div>}
      </Card><div className="mt-4 flex items-center justify-between"><Button variant="quiet" onClick={()=>step===0?navigate('/teams'):setStep(s=>s-1)}>{step===0?'Cancel':'Back'}</Button><Button onClick={next} disabled={loading} showArrow>{loading?'Finding your matches…':step===2?'Create team & find matches':step===3?'View my team':'Continue'}</Button></div></div>
    </div>
  </div>;
}
