const firstNames = ['Aarav','Maya','Ishaan','Zara','Dev','Ananya','Rohan','Leah','Kabir','Nina','Arjun','Tara','Neil','Aisha','Vihaan','Sara','Reyansh','Mira','Advik','Ira','Kian','Diya','Sam','Noor','Ayaan','Riya','Ethan','Amara','Ritvik','Jia'];
const lastNames = ['Shah','Mehta','Rao','Kapoor','Iyer','Patel','Nair','Khanna','Das','Singh'];
const skillSets = [['React','TypeScript','Figma'],['Python','Machine Learning','TensorFlow'],['Java','Spring Boot','SQL'],['UI Design','Figma','Prototyping'],['React Native','Flutter','Firebase'],['Python','Data Science','SQL'],['Node.js','AWS','Docker'],['Illustration','Brand Design','Figma']];
const colleges = ['Northstar Institute','Lakeview University','Cedar College','Eastbridge Tech'];
export const students = Array.from({ length: 30 }, (_, i) => ({
  id: `stu-${i + 1}`, role:'STUDENT', fullName: `${firstNames[i]} ${lastNames[i % lastNames.length]}`, email: `${firstNames[i].toLowerCase()}@northstar.edu`, collegeName: colleges[i % colleges.length], major: ['Computer Science','Product Design','Data Science','Information Systems'][i % 4], graduationYear: 2026 + (i % 3), avatarUrl: `https://i.pravatar.cc/160?img=${(i % 70) + 1}`, lookingForTeam: i % 4 !== 0, profileCompleteness: 58 + ((i * 7) % 43), skills: skillSets[i % skillSets.length].map((skillName, j) => ({ id: `${i}-${j}`, skillName, category: /React|TypeScript/.test(skillName) ? 'Frontend' : /Figma|Design|Illustration|Prototyping/.test(skillName) ? 'Design' : /Machine|Tensor|Data/.test(skillName) ? 'AI/ML' : 'Backend', proficiencyLevel: ['Intermediate','Advanced','Beginner'][(i + j) % 3] }))
}));
export const events = [
  { id:'evt-01', title:'Build for Tomorrow', organizer:'Northstar Innovation Lab', category:'Hackathon', scope:'Inter-college', mode:'Hybrid', date:'2026-10-18', deadline:'2026-10-10', teamSize:'2–4', color:'sage', description:'A weekend to make thoughtful technology for a more accessible, sustainable future.', skills:['React','Python','Product Design'], registrations:184 },
  { id:'evt-02', title:'Design, Actually', organizer:'Cedar Design Society', category:'Design sprint', scope:'Inter-college', mode:'In person', date:'2026-10-24', deadline:'2026-10-20', teamSize:'2–3', color:'peach', description:'Turn a real campus challenge into a prototype people love to use.', skills:['Figma','UI Design','Research'], registrations:96 },
  { id:'evt-03', title:'Campus Data Jam', organizer:'Lakeview Data Club', category:'Datathon', scope:'Intra-college', mode:'Online', date:'2026-11-02', deadline:'2026-10-28', teamSize:'2–5', color:'sky', description:'Explore open datasets and build a clear story from the numbers.', skills:['Python','SQL','Data Science'], registrations:72 },
  { id:'evt-04', title:'AI for Good Lab', organizer:'Eastbridge AI Collective', category:'Hackathon', scope:'Inter-college', mode:'In person', date:'2026-11-08', deadline:'2026-11-01', teamSize:'3–4', color:'butter', description:'A hands-on challenge for practical, human-centered machine learning.', skills:['Python','Machine Learning','TensorFlow'], registrations:211 },
  { id:'evt-05', title:'Mobile Maker Weekend', organizer:'Northstar Dev Guild', category:'Hackathon', scope:'Intra-college', mode:'Hybrid', date:'2026-11-15', deadline:'2026-11-08', teamSize:'2–4', color:'blush', description:'Make a small screen feel like a big idea with a polished mobile experience.', skills:['React Native','Flutter','UI Design'], registrations:58 },
  { id:'evt-06', title:'Open Source Sprint', organizer:'Cedar Computing', category:'Sprint', scope:'Inter-college', mode:'Online', date:'2026-11-22', deadline:'2026-11-19', teamSize:'1–4', color:'sage', description:'Collaborate on a project that keeps helping after the weekend ends.', skills:['Java','Node.js','Git'], registrations:139 },
  { id:'evt-07', title:'The Product Pitch', organizer:'Lakeview Founders', category:'Pitch challenge', scope:'Inter-college', mode:'In person', date:'2026-12-03', deadline:'2026-11-24', teamSize:'2–4', color:'peach', description:'Find a problem worth solving and pitch the first useful version.', skills:['Product Design','Research','Storytelling'], registrations:81 },
  { id:'evt-08', title:'Green City Challenge', organizer:'Eastbridge Sustainability', category:'Hackathon', scope:'Inter-college', mode:'Hybrid', date:'2026-12-11', deadline:'2026-12-03', teamSize:'3–5', color:'sky', description:'Create a digital tool for cleaner, kinder, more connected cities.', skills:['React','Data Science','Mapping'], registrations:167 },
  { id:'evt-09', title:'Cyber Safe Campus', organizer:'Northstar Security Club', category:'CTF', scope:'Intra-college', mode:'Online', date:'2026-12-16', deadline:'2026-12-12', teamSize:'2–4', color:'butter', description:'Work together through practical security puzzles and defense scenarios.', skills:['Python','Security','Networking'], registrations:103 },
  { id:'evt-10', title:'Creative Code Night', organizer:'Cedar Arts & Tech', category:'Creative coding', scope:'Inter-college', mode:'In person', date:'2026-12-20', deadline:'2026-12-18', teamSize:'1–3', color:'blush', description:'Make something playful where code meets motion, sound, and visual art.', skills:['JavaScript','Illustration','Creative Coding'], registrations:64 }
];
export const teams = Array.from({ length: 8 }, (_, i) => ({ id:`team-${i+1}`, name:['Soft Launch','Pixel Garden','Data Picnic','Kind Machines','Pocket Planet','Open Hands','Greenlight','Late Bloomers'][i], eventId:events[i % events.length].id, eventName:events[i % events.length].title, status:['Forming','Ready','Competing','Forming'][i % 4], project:['Campus companion','Accessible maps','Food waste finder','Study buddy'][i % 4], memberIds:[students[i].id, students[(i+7)%30].id, students[(i+14)%30].id].slice(0, 2 + i % 2), skillGaps:['Backend','Product Design'] }));
export const invitations = [
  { id:'inv-01', teamId:'team-2', teamName:'Pixel Garden', from:students[6], eventName:'Design, Actually', status:'pending' },
  { id:'inv-02', teamId:'team-4', teamName:'Kind Machines', from:students[11], eventName:'AI for Good Lab', status:'pending' },
  { id:'inv-03', teamId:'team-6', teamName:'Open Hands', from:students[3], eventName:'Build for Tomorrow', status:'accepted' },
  ...Array.from({length:5},(_,i)=>({id:`inv-${i+4}`,teamId:teams[i].id,teamName:teams[i].name,from:students[i+15],eventName:events[i].title,status:['declined','pending','accepted'][i%3]}))
];
export const notifications = [
  {id:'not-01',type:'invite',title:'You have a new team invite',body:'Pixel Garden invited you to Design, Actually.',time:'12 min ago',read:false},
  {id:'not-02',type:'event',title:'Registration closes soon',body:'Build for Tomorrow closes in 11 days.',time:'2 hours ago',read:false},
  {id:'not-03',type:'match',title:'A great teammate match',body:'Maya is a 92% match for your skills.',time:'Yesterday',read:true}
];
export const recommendations = (teamId) => students.filter(s => s.lookingForTeam).slice(0,8).map((student,i) => ({...student,matchScore:92 - (i*3),matchingSkills:student.skills.slice(0,2).map(s=>s.skillName),aiReason:`Strong ${i%2?'product':'technical'} fit, with complementary experience in ${student.skills[0].skillName}.`}));
