import React,{useEffect,useMemo,useRef,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {AnimatePresence,motion} from 'framer-motion';
import {ArrowRight,CalendarDays,Search,Sparkles,Users,UserRound,X} from 'lucide-react';
import {events,students} from '../api/mockData';

const pages=[{title:'Dashboard',category:'Pages',path:'/dashboard',icon:Sparkles},{title:'Events',category:'Pages',path:'/events',icon:CalendarDays},{title:'AI teammate finder',category:'Pages',path:'/assistant',icon:Users},{title:'My teams and invites',category:'Pages',path:'/teams',icon:Users},{title:'Student directory',category:'Pages',path:'/students',icon:UserRound},{title:'My profile',category:'Pages',path:'/profile',icon:UserRound}];
export function CommandPalette({isOpen,onClose,onOpen=()=>{}}){
  const [query,setQuery]=useState('');const [active,setActive]=useState(0);const inputRef=useRef(null);const navigate=useNavigate();
  const items=useMemo(()=>{const q=query.trim().toLowerCase();const all=[...pages,...events.map(e=>({title:e.title,category:'Events',path:`/events/${e.id}`,icon:CalendarDays,search:`${e.category} ${e.skills.join(' ')}`})),...students.map(s=>({title:s.fullName,category:`Student · ${s.major}`,path:`/students/${s.id}`,icon:UserRound,search:`${s.collegeName} ${s.skills.map(x=>x.skillName).join(' ')}`}))];return all.filter(item=>!q||`${item.title} ${item.category} ${item.search||''}`.toLowerCase().includes(q)).slice(0,12);},[query]);
  useEffect(()=>{const key=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(isOpen)onClose();else onOpen();}if(e.key==='Escape'&&isOpen)onClose();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[isOpen,onClose,onOpen]);
  useEffect(()=>{if(isOpen){setQuery('');setActive(0);requestAnimationFrame(()=>inputRef.current?.focus());}},[isOpen]);
  const select=(item)=>{if(!item)return;navigate(item.path);onClose();};
  const handleKey=(e)=>{if(e.key==='ArrowDown'){e.preventDefault();setActive(x=>Math.min(x+1,items.length-1));}else if(e.key==='ArrowUp'){e.preventDefault();setActive(x=>Math.max(x-1,0));}else if(e.key==='Enter'){e.preventDefault();select(items[active]);}};
  return <AnimatePresence>{isOpen&&<motion.div className="fixed inset-0 z-[100] flex items-start justify-center bg-[#141414]/40 px-3 pt-[12vh] backdrop-blur-sm sm:px-5" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><motion.section role="dialog" aria-modal="true" aria-label="Search SkillSync" initial={{opacity:0,y:-10,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-8,scale:.98}} className="w-full max-w-xl overflow-hidden rounded-[26px] bg-[#F6F3EE] text-[#141414] shadow-2xl dark:bg-[#24221e] dark:text-white"><div className="flex items-center gap-3 border-b border-black/[.07] px-4 dark:border-white/[.08]"><Search size={19} className="shrink-0 text-[#888176]"/><input ref={inputRef} role="combobox" aria-expanded="true" aria-controls="command-results" aria-activedescendant={items[active]?`command-${active}`:undefined} value={query} onChange={e=>{setQuery(e.target.value);setActive(0);}} onKeyDown={handleKey} placeholder="Search events, students, pages…" className="min-w-0 flex-1 bg-transparent py-5 text-sm outline-none placeholder:text-[#979084]"/><button onClick={onClose} aria-label="Close search" className="rounded-full p-2 hover:bg-black/5 dark:hover:bg-white/10"><X size={17}/></button></div><div id="command-results" role="listbox" aria-label="Search results" className="max-h-[min(65vh,470px)] overflow-y-auto p-2">{items.length===0?<div className="px-5 py-10 text-center"><Search className="mx-auto text-[#a29b90]"/><p className="mt-3 text-sm font-semibold">Nothing found for “{query}”</p><p className="mt-1 text-xs text-[#898278]">Try a skill, an event, or a student’s name.</p></div>:items.map((item,index)=>{const Icon=item.icon;return <button key={`${item.category}-${item.title}`} id={`command-${index}`} role="option" aria-selected={active===index} onMouseEnter={()=>setActive(index)} onClick={()=>select(item)} className={`flex w-full items-center gap-3 rounded-2xl px-3 py-3 text-left transition ${active===index?'bg-white shadow-sm dark:bg-white/10':'hover:bg-white/70 dark:hover:bg-white/[.06]'}`}><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#D8E8F4] text-[#387f9a] dark:bg-[#29363d] dark:text-[#add7e5]"><Icon size={17}/></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{item.title}</span><span className="block truncate text-[11px] text-[#898278]">{item.category}</span></span><ArrowRight size={14} className="text-[#9a9489]"/></button>;})}</div><div className="flex items-center justify-between border-t border-black/[.06] px-4 py-3 text-[10px] text-[#898278] dark:border-white/[.08]"><span>Search events, students and pages</span><span>↑ ↓ navigate · ↵ open · esc close</span></div></motion.section></motion.div>}</AnimatePresence>;
}
