import React,{useCallback,useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {Command,LogOut,Moon,Search,Sun,UserRound,Bell,ChevronDown,Sparkles,CalendarDays,ShieldCheck} from 'lucide-react';
import {useAuth} from '../context/AuthContext';
import {useTheme} from '../context/ThemeContext';
import {CommandPalette} from './CommandPalette';
import {notificationsApi} from '../api/client';
import {Avatar} from './ui';

export function Navbar(){
  const {user,logout}=useAuth();const {isDark,toggleTheme}=useTheme();const navigate=useNavigate();const [palette,setPalette]=useState(false);const [menu,setMenu]=useState(false);const [unread,setUnread]=useState(0);
  useEffect(()=>{notificationsApi.list().then(({data})=>setUnread(data.filter(n=>!n.read).length)).catch(()=>{});},[]);
  const openPalette=useCallback(()=>setPalette(true),[]);
  return <><header className="sticky top-0 z-40 border-b border-black/[.06] bg-[#F6F3EE]/90 backdrop-blur-xl dark:border-white/[.08] dark:bg-[#151412]/90"><div className="mx-auto flex h-[68px] max-w-[1500px] items-center justify-between gap-3 px-4 sm:px-6 lg:px-8"><Link to="/dashboard" className="flex items-center gap-2.5"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#141414] text-white dark:bg-white dark:text-[#141414]"><Sparkles size={18}/></span><span className="display-font text-lg font-extrabold tracking-tight">skill<span className="font-medium">sync</span></span></Link>
    <button onClick={openPalette} className="hidden max-w-md flex-1 items-center gap-3 rounded-full bg-white/75 px-4 py-2.5 text-left text-xs text-[#8b857b] shadow-sm hover:bg-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#3986a0] dark:bg-white/[.07] dark:text-[#d0c9be] md:flex"><Search size={15}/><span className="flex-1">Search events, students, pages…</span><kbd className="flex items-center gap-1 rounded-md bg-black/5 px-1.5 py-1 text-[10px] dark:bg-white/10"><Command size={10}/> K</kbd></button>
    <div className="flex items-center gap-1 sm:gap-2"><button onClick={openPalette} aria-label="Search" className="grid h-10 w-10 place-items-center rounded-full hover:bg-black/5 md:hidden dark:hover:bg-white/10"><Search size={18}/></button><button onClick={toggleTheme} aria-label={`Switch to ${isDark?'light':'dark'} mode`} className="grid h-10 w-10 place-items-center rounded-full hover:bg-black/5 dark:hover:bg-white/10">{isDark?<Sun size={18}/>:<Moon size={18}/>}</button><button onClick={()=>navigate('/teams')} aria-label={`${unread} notifications`} className="relative grid h-10 w-10 place-items-center rounded-full hover:bg-black/5 dark:hover:bg-white/10"><Bell size={18}/>{unread>0&&<span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-[#dd7b69] ring-2 ring-[#F6F3EE] dark:ring-[#151412]"/>}</button><div className="relative"><button onClick={()=>setMenu(v=>!v)} aria-expanded={menu} aria-label="Open account menu" className="flex items-center gap-2 rounded-full p-1 hover:bg-black/5 dark:hover:bg-white/10"><Avatar src={user?.avatarUrl} name={user?.fullName||'Student'} size={34}/><span className="hidden max-w-28 truncate text-xs font-bold sm:inline">{user?.fullName}</span><ChevronDown size={14} className="hidden sm:block"/></button>{menu&&<div className="absolute right-0 top-12 z-50 w-60 rounded-2xl bg-white p-2 text-[#141414] shadow-xl dark:bg-[#282621] dark:text-white"><div className="border-b border-black/5 px-3 py-2 dark:border-white/10"><p className="truncate text-sm font-bold">{user?.fullName}</p><p className="truncate text-xs text-[#847e74]">{user?.email}</p><p className="mt-2 text-xs font-semibold text-[#547d4c]">{user?.profileCompleteness||60}% profile complete</p></div>{(user?.role==='ORGANIZER'||user?.role==='ADMIN')&&<button onClick={()=>{navigate('/studio');setMenu(false);}} className="flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-left text-sm hover:bg-black/5 dark:hover:bg-white/10"><CalendarDays size={15}/> Organizer studio</button>}{user?.role==='ADMIN'&&<button onClick={()=>{navigate('/admin');setMenu(false);}} className="flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-left text-sm hover:bg-black/5 dark:hover:bg-white/10"><ShieldCheck size={15}/> Admin overview</button>}<button onClick={()=>{navigate('/profile');setMenu(false);}} className="flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-left text-sm hover:bg-black/5 dark:hover:bg-white/10"><UserRound size={15}/> My profile</button><button onClick={()=>{logout();setMenu(false);navigate('/');}} className="flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-left text-sm text-[#a34d48] hover:bg-[#F8D9DF]/60 dark:hover:bg-white/10"><LogOut size={15}/> Sign out</button></div>}</div></div></div></header><CommandPalette isOpen={palette} onClose={()=>setPalette(false)} onOpen={openPalette}/></>;
}
