import React from 'react';
import { ArrowRight, X } from 'lucide-react';

export function Button({ children, variant='primary', className='', showArrow=false, ...props }) {
  const variants={primary:'bg-[#141414] text-white hover:bg-[#30302d] dark:bg-[#f6f3ee] dark:text-[#141414] dark:hover:bg-white', secondary:'bg-white/80 text-[#141414] border border-black/10 hover:bg-white dark:bg-white/10 dark:text-white dark:border-white/15', quiet:'bg-transparent text-[#141414] hover:bg-black/5 dark:text-white dark:hover:bg-white/10'};
  return <button className={`group inline-flex items-center justify-center gap-2 rounded-full px-5 py-3 text-sm font-semibold transition duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#31829a] focus-visible:ring-offset-2 ${variants[variant]} ${className}`} {...props}>{children}{showArrow && <ArrowRight size={16} className="arrow-slide" aria-hidden="true" />}</button>;
}
export function Card({ children, color='white', className='', ...props }) {
  const backgrounds={white:'bg-white/85 dark:bg-[#22211e]',sage:'bg-[#DCE8D6] dark:bg-[#313a2f]',peach:'bg-[#FBE1D0] dark:bg-[#40312b]',sky:'bg-[#D8E8F4] dark:bg-[#29363d]',butter:'bg-[#FBEEC3] dark:bg-[#403b2a]',blush:'bg-[#F8D9DF] dark:bg-[#402d33]'};
  return <section className={`rounded-[28px] ${backgrounds[color] || backgrounds.white} ${className}`} {...props}>{children}</section>;
}
export function Badge({ children, color='ink', className='' }) {
  const styles={ink:'bg-black/5 text-[#35332f] dark:bg-white/10 dark:text-white',green:'bg-[#e6f2e4] text-[#315e37] dark:bg-[#2e422f] dark:text-[#d1ead0]',amber:'bg-[#fbefc9] text-[#765114] dark:bg-[#443a24] dark:text-[#f5dfa2]',pink:'bg-[#f9e2e6] text-[#874254] dark:bg-[#442c33] dark:text-[#f5c3cf]',sky:'bg-[#e2f0f5] text-[#225e75] dark:bg-[#293b42] dark:text-[#bde2ee]'};
  return <span className={`inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold ${styles[color] || styles.ink} ${className}`}>{children}</span>;
}
export function Panel({ children, className='', ...props }) { return <div className={`rounded-3xl bg-white/75 p-5 panel-shadow dark:bg-white/[.06] ${className}`} {...props}>{children}</div>; }
export function Input({ label, error, className='', ...props }) { return <label className="block text-sm font-semibold text-[#33312d] dark:text-[#eee9e0]">{label}<input className={`auth-input mt-2 block font-normal ${error?'!border-[#b94848]':''} ${className}`} {...props} />{error && <span className="mt-1 block text-xs font-medium text-[#a23232] dark:text-[#ffb0a5]">{error}</span>}</label>; }
export function SkillChip({ children, tone='sky' }) { const styles={sky:'bg-[#e5f1f6] text-[#245d73] dark:bg-[#263a42] dark:text-[#bbdeeb]',green:'bg-[#e6f0e1] text-[#3a6338] dark:bg-[#2b3d2a] dark:text-[#cde2c3]',pink:'bg-[#f8e4e6] text-[#8b4a58] dark:bg-[#442c33] dark:text-[#efc0ca]',amber:'bg-[#fbf0ce] text-[#795a17] dark:bg-[#443a25] dark:text-[#efdda8]',coral:'bg-[#fbe5db] text-[#8a4f3b] dark:bg-[#45332d] dark:text-[#f1c6ae]',teal:'bg-[#e1f0eb] text-[#286961] dark:bg-[#283e39] dark:text-[#b9e0d3]'}; return <span className={`inline-flex rounded-full px-3 py-1.5 text-xs font-semibold ${styles[tone]||styles.sky}`}>{children}</span>; }
export function Avatar({ src, name='Student', size=44, className='' }) { return <img src={src || `https://i.pravatar.cc/100?u=${encodeURIComponent(name)}`} alt={name} width={size} height={size} className={`rounded-full object-cover ${className}`} />; }
export function Tabs({ items, value, onChange, label='Sections' }) { return <div role="tablist" aria-label={label} className="flex flex-wrap gap-1 rounded-full bg-black/5 p-1 dark:bg-white/10">{items.map(item=><button key={item.value} id={`tab-${item.value}`} role="tab" aria-selected={value===item.value} aria-controls={`panel-${item.value}`} onClick={()=>onChange(item.value)} className={`rounded-full px-4 py-2 text-sm font-semibold transition ${value===item.value?'bg-white shadow-sm dark:bg-[#36342f]':'text-[#716d65] dark:text-[#c9c2b8]'}`}>{item.label}</button>)}</div>; }
export function Modal({ open, title, onClose, children, className='' }) { React.useEffect(()=>{if(!open)return;const handle=(event)=>{if(event.key==='Escape')onClose?.();};window.addEventListener('keydown',handle);return()=>window.removeEventListener('keydown',handle);},[open,onClose]); if(!open)return null; return <div className="fixed inset-0 z-[100] grid place-items-center overflow-y-auto bg-[#141414]/45 p-4 backdrop-blur-sm" onMouseDown={e=>{if(e.target===e.currentTarget)onClose?.();}}><section role="dialog" aria-modal="true" aria-labelledby="skillsync-modal-title" className={`w-full max-w-lg rounded-[28px] bg-[#F6F3EE] p-6 text-[#141414] panel-shadow dark:bg-[#22211e] dark:text-white ${className}`}><div className="mb-5 flex items-start justify-between gap-4"><h2 id="skillsync-modal-title" className="display-font text-xl font-extrabold">{title}</h2><button onClick={onClose} aria-label="Close dialog" className="rounded-full p-2 hover:bg-black/5 dark:hover:bg-white/10"><X size={18}/></button></div>{children}</section></div>; }
export function ProgressRing({ value=0, size=58, stroke=5, label }) { const radius=(size-stroke)/2; const circumference=2*Math.PI*radius; const progress=Math.min(100,Math.max(0,value)); return <div className="relative inline-grid place-items-center" style={{width:size,height:size}} role="img" aria-label={label || `${progress}% complete`}><svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} className="-rotate-90"><circle cx={size/2} cy={size/2} r={radius} fill="none" stroke="currentColor" strokeOpacity=".12" strokeWidth={stroke}/><circle cx={size/2} cy={size/2} r={radius} fill="none" stroke="#72a76a" strokeLinecap="round" strokeWidth={stroke} strokeDasharray={circumference} strokeDashoffset={circumference*(1-progress/100)}/></svg><span className="absolute text-xs font-bold">{progress}%</span></div>; }
